import { createClient } from 'https://esm.sh/@supabase/supabase-js@2.57.4';
const CORS={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'authorization, x-client-info, apikey, content-type','Access-Control-Allow-Methods':'POST, OPTIONS'};
const json=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:{...CORS,'Content-Type':'application/json'}});
const cleanIsbn=(v:unknown)=>String(v??'').replace(/[^0-9Xx]/g,'').toUpperCase();
async function fetchJson(url:string){try{const r=await fetch(url,{headers:{'User-Agent':'LibrarianGPT/1.2 personal library'}});if(!r.ok)return null;return await r.json()}catch{return null}}
async function usableImage(url:string|null){if(!url)return null;try{const r=await fetch(url,{redirect:'follow',headers:{'User-Agent':'LibrarianGPT/1.2','Accept':'image/*,*/*;q=0.8'}});const type=r.headers.get('content-type')||'';if(!r.ok||!type.startsWith('image/'))return null;const bytes=new Uint8Array(await r.arrayBuffer());if(bytes.byteLength<1000)return null;return {url:r.url||url,type,bytes}}catch{return null}}
function extFor(type:string){if(type.includes('png'))return'png';if(type.includes('webp'))return'webp';return'jpg'}
async function archive(admin:any,bookId:string,editionId:string|null,image:any){const path=`${bookId}/${editionId||'book'}.${extFor(image.type)}`;const up=await admin.storage.from('book-covers').upload(path,image.bytes,{contentType:image.type,upsert:true,cacheControl:'31536000'});if(up.error)throw up.error;return admin.storage.from('book-covers').getPublicUrl(path).data.publicUrl}
function gid(v:any,t:string){return v?.industryIdentifiers?.find((x:any)=>x?.type===t)?.identifier??null}
Deno.serve(async(req:Request)=>{if(req.method==='OPTIONS')return new Response('ok',{headers:CORS});if(req.method!=='POST')return json({error:'POST required'},405);try{
 const auth=req.headers.get('Authorization');if(!auth)return json({error:'Authentication required'},401);
 const url=Deno.env.get('SUPABASE_URL')!,anon=Deno.env.get('SUPABASE_ANON_KEY')!,service=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;
 const user=createClient(url,anon,{global:{headers:{Authorization:auth}}});const u=await user.auth.getUser();if(u.error||!u.data.user)return json({error:'Invalid session'},401);const owner=await user.rpc('is_library_owner');if(owner.error||owner.data!==true)return json({error:'Not authorized'},403);
 const body=await req.json();const bookId=String(body?.book_id||''),isbn=cleanIsbn(body?.isbn);if(!bookId||!isbn)return json({error:'book_id and isbn required'},400);
 const admin=createClient(url,service);const entry=await admin.from('library_entries').select('current_edition_id').eq('book_id',bookId).single();if(entry.error||!entry.data?.current_edition_id)return json({error:'Owned edition not found'},404);
 const ed=await admin.from('editions').select('id,isbn10,isbn13,cover_locked,cover_url').eq('id',entry.data.current_edition_id).single();if(ed.error||!ed.data)return json({error:'Edition not found'},404);if(ed.data.cover_locked&&ed.data.cover_url)return json({ok:true,cover_url:ed.data.cover_url,locked:true});
 const ids=[ed.data.isbn10,ed.data.isbn13].map(cleanIsbn).filter(Boolean);if(!ids.includes(isbn))return json({error:'ISBN does not match current owned edition'},409);
 let image:any=null,source:string|null=null,olEdition:string|null=null,olWork:string|null=null,gVolume:string|null=null;
 const ol=await fetchJson(`https://openlibrary.org/isbn/${encodeURIComponent(isbn)}.json`);olEdition=String(ol?.key||'').match(/\/books\/(OL\d+M)/)?.[1]||null;olWork=String(ol?.works?.[0]?.key||'').match(/\/works\/(OL\d+W)/)?.[1]||null;
 const coverIds=Array.isArray(ol?.covers)?ol.covers:[];for(const cid of coverIds){image=await usableImage(`https://covers.openlibrary.org/b/id/${cid}-L.jpg?default=false`);if(image){source='Open Library';break}}
 if(!image){image=await usableImage(`https://covers.openlibrary.org/isbn/${isbn}-L.jpg?default=false`);if(image)source='Open Library'}
 if(!image){const gUrl=new URL('https://www.googleapis.com/books/v1/volumes');gUrl.searchParams.set('q',`isbn:${isbn}`);gUrl.searchParams.set('maxResults','10');gUrl.searchParams.set('projection','full');const key=Deno.env.get('GOOGLE_BOOKS_API_KEY');if(key)gUrl.searchParams.set('key',key);const g=await fetchJson(gUrl.toString());const items=Array.isArray(g?.items)?g.items:[];const item=items.find((x:any)=>[gid(x?.volumeInfo,'ISBN_10'),gid(x?.volumeInfo,'ISBN_13')].map(cleanIsbn).includes(isbn))||items[0]||null;if(item){gVolume=item.id||null;const links=item?.volumeInfo?.imageLinks||{};for(const c of [links.extraLarge,links.large,links.medium,links.small,links.thumbnail,links.smallThumbnail].filter(Boolean).map((x:string)=>String(x).replace(/^http:/,'https:'))){image=await usableImage(c);if(image){source='Google Books';break}}}}
 if(!image)return json({error:'No usable exact-edition cover found'},404);const stable=await archive(admin,bookId,ed.data.id,image);
 await admin.from('editions').update({cover_url:stable,cover_source:`${source} · archived`,cover_verified:true,open_library_edition_id:olEdition,open_library_work_id:olWork,google_books_volume_id:gVolume,metadata_last_fetched_at:new Date().toISOString()}).eq('id',ed.data.id);
 await admin.from('books').update({cover_url_preferred:stable,cover_source:`${source} · archived`,cover_verified:true}).eq('id',bookId);
 await admin.from('library_events').insert({user_id:u.data.user.id,book_id:bookId,event_type:'owned_cover_refreshed',source:'metadata_api',payload:{isbn,edition_id:ed.data.id,cover_source:source,cover_url:stable}});
 return json({ok:true,book_id:bookId,edition_id:ed.data.id,cover_url:stable,cover_source:source,archived:true});
}catch(e){console.error(e);return json({error:e?.message||'Cover refresh failed'},500)}});
