import { createClient } from 'https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm';
import { SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY } from './supabase-config.js';

const supabase=createClient(SUPABASE_URL,SUPABASE_PUBLISHABLE_KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});
const modalRoot=document.querySelector('#modal-root');
const toastNode=document.querySelector('#toast');
const COVER_OVERRIDE_KEY='library-cover-overrides-v14';
const repairedThisSession=new Set();
let repairRunning=false;

const esc=(v='')=>String(v).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;');
function toast(message,error=false){if(!toastNode)return;toastNode.textContent=message;toastNode.className=`toast show${error?' error':''}`;clearTimeout(toastNode._v14);toastNode._v14=setTimeout(()=>toastNode.className='toast',3200);}
function readOverrides(){try{return JSON.parse(localStorage.getItem(COVER_OVERRIDE_KEY)||'{}')}catch{return{}}}
function writeOverride(id,title,url){const all=readOverrides();all[id]={title,url};localStorage.setItem(COVER_OVERRIDE_KEY,JSON.stringify(all));paintCover(id,title,url);}
function escSel(v){return window.CSS?.escape?CSS.escape(String(v)):String(v).replace(/["\\]/g,'\\$&')}
function paintCover(id,title,url){if(!url)return;document.querySelectorAll(`[data-book-id="${escSel(id)}"] .cover`).forEach(c=>put(c));document.querySelectorAll('.detail-header').forEach(d=>{const bid=d.dataset.bookId;const h=d.querySelector('h1')?.textContent?.trim();if(bid===id||h===title)put(d.querySelector('.cover'))});function put(c){if(!c)return;let img=c.querySelector('img');if(!img){img=document.createElement('img');img.alt=`Cover of ${title}`;img.loading='lazy';c.prepend(img)}img.src=url;}}
function paintOverrides(){const all=readOverrides();for(const [id,v] of Object.entries(all))paintCover(id,v.title,v.url)}

async function invoke(name,body){const {data,error}=await supabase.functions.invoke(name,{body});if(error){try{if(error.context instanceof Response){const p=await error.context.clone().json();throw new Error(p?.error||error.message)}}catch(e){if(e instanceof Error&&e.message!==error.message)throw e}throw error}if(data?.error)throw new Error(data.error);return data}
function openModal(html){modalRoot.innerHTML=`<div class="modal-backdrop"><div class="modal">${html}</div></div>`;modalRoot.querySelectorAll('[data-v14-close]').forEach(b=>b.addEventListener('click',()=>modalRoot.innerHTML=''));modalRoot.querySelector('.modal-backdrop')?.addEventListener('click',e=>{if(e.target.classList.contains('modal-backdrop'))modalRoot.innerHTML=''})}

async function getBook(id){const {data,error}=await supabase.from('v_library').select('*').eq('id',id).single();if(error)throw error;return data}
async function savedCandidates(id){const {data,error}=await supabase.from('book_cover_candidates').select('*').eq('book_id',id).order('selected',{ascending:false}).order('exact_edition',{ascending:false}).order('updated_at',{ascending:false}).limit(30);if(error)throw error;return data||[]}
function renderCoverPicker(book,candidates,searching=false){openModal(`<h2>Edit cover</h2><p>${book.ownership_status==='Owned'?'Exact-edition artwork is prioritised.':'Reference artwork is used until you own a specific edition.'} Saved choices appear immediately.</p><div class="cover-picker-toolbar"><span class="cover-picker-status">${candidates.length?`${candidates.length} saved option${candidates.length===1?'':'s'}`:'No saved artwork yet.'}</span><button class="btn" id="v14-find-covers" type="button">${searching?'Searching…':'Find more covers'}</button></div><div class="cover-picker-grid">${candidates.map(c=>`<button class="cover-option ${c.selected?'selected':''}" data-v14-candidate="${c.id}" type="button"><img src="${esc(c.source_url)}" alt="${esc(c.provider)} cover" loading="lazy" onerror="this.closest('button').style.display='none'"><span>${esc(c.provider)}${c.exact_edition?' · exact ISBN':''}</span></button>`).join('')||'<p>No artwork is cached yet. Use “Find more covers” to search the providers.</p>'}</div><form id="v14-custom-cover" class="form-stack"><div class="field"><label for="v14-cover-url">Or use an image URL</label><input class="input" id="v14-cover-url" type="url" placeholder="https://…"></div><div class="modal-actions"><button class="btn" type="button" data-v14-close>Cancel</button><button class="btn btn-primary" type="submit">Use URL</button></div></form>`);
 modalRoot.querySelectorAll('[data-v14-candidate]').forEach(b=>b.addEventListener('click',()=>chooseCover(book,b.dataset.v14Candidate,b)));
 modalRoot.querySelector('#v14-find-covers')?.addEventListener('click',async e=>{const btn=e.currentTarget;btn.disabled=true;btn.textContent='Searching…';try{const r=await invoke('cover-options',{book_id:book.id,refresh:true});renderCoverPicker(book,r.candidates||[],false)}catch(err){toast(err.message||'Could not search covers',true);btn.disabled=false;btn.textContent='Find more covers'}});
 modalRoot.querySelector('#v14-custom-cover')?.addEventListener('submit',async e=>{e.preventDefault();const url=e.currentTarget['v14-cover-url'].value.trim();if(!url)return;const {data,error}=await supabase.from('book_cover_candidates').upsert({book_id:book.id,edition_id:book.display_edition_id||null,provider:'Manual URL',source_label:'Custom URL',source_url:url,exact_edition:book.ownership_status==='Owned'},{onConflict:'book_id,source_url'}).select('id').single();if(error){toast(error.message,true);return}await chooseCover(book,data.id,e.currentTarget.querySelector('button[type="submit"]'))});
}
async function openFastCoverPicker(id){try{const [book,candidates]=await Promise.all([getBook(id),savedCandidates(id)]);renderCoverPicker(book,candidates,false)}catch(e){toast(e.message||'Could not load saved covers',true)}}
async function chooseCover(book,candidateId,button){button.disabled=true;try{const r=await invoke('select-cover',{book_id:book.id,candidate_id:candidateId,lock:true});if(r?.cover_url)writeOverride(book.id,book.title,r.cover_url);await window.LibraryDataCache?.clear?.();modalRoot.innerHTML='';toast('Cover saved.')}catch(e){toast(e.message||'Could not save cover',true);button.disabled=false}}

document.addEventListener('click',e=>{const b=e.target.closest('[data-v4-cover]');if(!b)return;e.preventDefault();e.stopImmediatePropagation();openFastCoverPicker(b.dataset.v4Cover)},{capture:true});

const sleep=ms=>new Promise(r=>setTimeout(r,ms));
async function repairOne(book){if(repairedThisSession.has(book.id))return;repairedThisSession.add(book.id);try{await invoke('content-enrichment',{book_id:book.id,force:true})}catch(e){console.info(`[Library] background metadata repair skipped for ${book.title}:`,e.message)}}
async function runChunk(items){let i=0;async function worker(){while(i<items.length){const book=items[i++];await repairOne(book);await sleep(250)}}await Promise.all([worker(),worker()])}
async function backgroundRepair(){if(repairRunning||document.hidden||!navigator.onLine)return;repairRunning=true;try{const {data:{session}}=await supabase.auth.getSession();if(!session)return;const [{data:lib,error:le},{data:core,error:ce}]=await Promise.all([supabase.from('v_library').select('id,title,ownership_status,overall_status,display_edition_id,synopsis,cover_url,total_pages,edition_page_count'),supabase.from('books').select('id,metadata_status,metadata_retry_after')]);if(le||ce||!lib?.length)return;const cMap=new Map((core||[]).map(x=>[x.id,x]));const now=Date.now();const todo=lib.filter(b=>{const c=cMap.get(b.id)||{};const retry=!c.metadata_retry_after||new Date(c.metadata_retry_after).getTime()<=now;const incomplete=!b.synopsis||!b.display_edition_id||!b.total_pages||!b.cover_url;return retry&&incomplete&&!repairedThisSession.has(b.id)&&c.metadata_status!=='ambiguous'});for(let n=0;n<todo.length;n+=10){if(document.hidden)break;await runChunk(todo.slice(n,n+10));await window.LibraryDataCache?.clear?.();if(n+10<todo.length)await sleep(12000)}}catch(e){console.info('[Library] background repair paused:',e.message)}finally{repairRunning=false}}

function refreshCurrentDetail(bookId){try{localStorage.removeItem('library-detail-cache-v4')}catch{}const detail=document.querySelector('.detail-header');if(!detail)return;const current=detail.dataset.bookId;if(current&&bookId&&current!==bookId)return;detail.removeAttribute('data-library-detail');delete detail.dataset.bookId;const marker=document.createComment('metadata refreshed');detail.append(marker);marker.remove();}
window.addEventListener('library-enrichment-complete',async e=>{await window.LibraryDataCache?.clear?.();refreshCurrentDetail(e.detail?.bookId||null)});

if(document.readyState==='complete')setTimeout(backgroundRepair,900);else window.addEventListener('load',()=>setTimeout(backgroundRepair,900));window.addEventListener('online',()=>setTimeout(backgroundRepair,800));document.addEventListener('visibilitychange',()=>{if(!document.hidden)setTimeout(backgroundRepair,1000)});supabase.auth.onAuthStateChange((_e,s)=>{if(s)setTimeout(backgroundRepair,1000)});

new MutationObserver(()=>requestAnimationFrame(paintOverrides)).observe(document.querySelector('#app')||document.body,{childList:true,subtree:true});paintOverrides();
