import { createClient } from 'https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm';
import { SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY } from './supabase-config.js';

const supabase=createClient(SUPABASE_URL,SUPABASE_PUBLISHABLE_KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});
const modalRoot=document.querySelector('#modal-root');
const toastNode=document.querySelector('#toast');
const COVER_OVERRIDE_KEY='library-cover-overrides-v14';
const PROGRESS_OVERRIDE_KEY='library-progress-overrides-v14';
const repairedThisSession=new Set();
let repairRunning=false;

const esc=(v='')=>String(v).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;');
const fmtRating=v=>v==null?'—':Number(v).toFixed(2);
function toast(message,error=false){if(!toastNode)return;toastNode.textContent=message;toastNode.className=`toast show${error?' error':''}`;clearTimeout(toastNode._v14);toastNode._v14=setTimeout(()=>toastNode.className='toast',3200);}
function readJson(key){try{return JSON.parse(localStorage.getItem(key)||'{}')}catch{return{}}}
function readOverrides(){return readJson(COVER_OVERRIDE_KEY)}
function writeOverride(id,title,url){const all=readOverrides();all[id]={title,url};localStorage.setItem(COVER_OVERRIDE_KEY,JSON.stringify(all));paintCover(id,title,url);}
function progressOverrides(){return readJson(PROGRESS_OVERRIDE_KEY)}
function writeProgressOverride(book){const all=progressOverrides();all[book.id]={savedAt:Date.now(),current_page:book.current_page,total_pages:book.total_pages,progress_percent:book.progress_percent,current_chapter_number:book.current_chapter_number||null,current_chapter_title:book.current_chapter_title||null,current_chapter_type:book.current_chapter_type||null};localStorage.setItem(PROGRESS_OVERRIDE_KEY,JSON.stringify(all));paintProgress(book.id,all[book.id]);}
function escSel(v){return window.CSS?.escape?CSS.escape(String(v)):String(v).replace(/["\\]/g,'\\$&')}
function paintCover(id,title,url){if(!url)return;document.querySelectorAll(`[data-book-id="${escSel(id)}"] .cover`).forEach(c=>put(c));document.querySelectorAll('.detail-header').forEach(d=>{const bid=d.dataset.bookId;const h=d.querySelector('h1')?.textContent?.trim();if(bid===id||h===title)put(d.querySelector('.cover'))});function put(c){if(!c)return;let img=c.querySelector('img');if(!img){img=document.createElement('img');img.alt=`Cover of ${title}`;img.loading='lazy';c.prepend(img)}img.src=url;}}
function paintOverrides(){const all=readOverrides();for(const [id,v] of Object.entries(all))paintCover(id,v.title,v.url)}
function chapterText(v){const n=String(v.current_chapter_number||'').trim(),t=String(v.current_chapter_title||'').trim(),type=String(v.current_chapter_type||'chapter');if(!n&&!t)return'';if(type==='chapter'&&n)return(!t||t.toLowerCase()===`chapter ${n}`.toLowerCase())?`Chapter ${n}`:`Chapter ${n}: ${t}`;return t||`Chapter ${n}`}
function paintProgress(id,v){if(!v)return;const blocks=new Set();document.querySelectorAll(`[data-book-id="${escSel(id)}"] .progress-block`).forEach(x=>blocks.add(x));document.querySelectorAll(`.detail-header[data-book-id="${escSel(id)}"] .progress-block`).forEach(x=>blocks.add(x));blocks.forEach(block=>{const spans=block.querySelectorAll('.progress-meta span');if(spans[0])spans[0].textContent=v.total_pages?`Page ${v.current_page??0} of ${v.total_pages}`:`Page ${v.current_page??0}`;if(spans[1])spans[1].textContent=v.total_pages?`${Math.round(Number(v.progress_percent)||((Number(v.current_page)||0)/Number(v.total_pages)*100))}%`:'';const fill=block.querySelector('.progress-fill');const pct=v.total_pages?Math.max(0,Math.min(100,Number(v.progress_percent)||((Number(v.current_page)||0)/Number(v.total_pages)*100))):0;if(fill)fill.style.setProperty('--progress',`${pct}%`);const label=chapterText(v);let line=block.querySelector('.chapter-progress-line');if(label){if(!line){line=document.createElement('div');line.className='chapter-progress-line';const meta=block.querySelector('.progress-meta');meta?.insertAdjacentElement('afterend',line)}line.textContent=label;line.title=label}else line?.remove()})}
function paintProgressOverrides(){const all=progressOverrides(),now=Date.now();for(const [id,v] of Object.entries(all)){if(now-Number(v.savedAt||0)<24*60*60*1000)paintProgress(id,v)}}
function reconcileProgressOverrides(rows=[]){const all=progressOverrides();let changed=false;for(const row of rows){const o=all[row.id];if(!o)continue;if(Number(o.current_page)===Number(row.current_page)&&Number(o.total_pages||0)===Number(row.total_pages||0)){delete all[row.id];changed=true}else if(Date.now()-Number(o.savedAt||0)>24*60*60*1000){delete all[row.id];changed=true}}if(changed)localStorage.setItem(PROGRESS_OVERRIDE_KEY,JSON.stringify(all))}

async function invoke(name,body){const {data,error}=await supabase.functions.invoke(name,{body});if(error){try{if(error.context instanceof Response){const p=await error.context.clone().json();throw new Error(p?.error||error.message)}}catch(e){if(e instanceof Error&&e.message!==error.message)throw e}throw error}if(data?.error)throw new Error(data.error);return data}
function openModal(html){modalRoot.innerHTML=`<div class="modal-backdrop"><div class="modal">${html}</div></div>`;modalRoot.querySelectorAll('[data-v14-close]').forEach(b=>b.addEventListener('click',()=>modalRoot.innerHTML=''));modalRoot.querySelector('.modal-backdrop')?.addEventListener('click',e=>{if(e.target.classList.contains('modal-backdrop'))modalRoot.innerHTML=''})}
async function getBook(id){const {data,error}=await supabase.from('v_library').select('*').eq('id',id).single();if(error)throw error;return data}

async function savedCandidates(id){const {data,error}=await supabase.from('book_cover_candidates').select('*').eq('book_id',id).order('selected',{ascending:false}).order('exact_edition',{ascending:false}).order('updated_at',{ascending:false}).limit(30);if(error)throw error;return data||[]}
function renderCoverPicker(book,candidates,searching=false){openModal(`<h2>Edit cover</h2><p>${book.ownership_status==='Owned'?'Exact-edition artwork is prioritised.':'Reference artwork is used until you own a specific edition.'} Saved choices appear immediately.</p><div class="cover-picker-toolbar"><span class="cover-picker-status">${candidates.length?`${candidates.length} saved option${candidates.length===1?'':'s'}`:'No saved artwork yet.'}</span><button class="btn" id="v14-find-covers" type="button">${searching?'Searching…':'Find more covers'}</button></div><div class="cover-picker-grid">${candidates.map(c=>`<button class="cover-option ${c.selected?'selected':''}" data-v14-candidate="${c.id}" type="button"><img src="${esc(c.source_url)}" alt="${esc(c.provider)} cover" loading="lazy" onerror="this.closest('button').style.display='none'"><span>${esc(c.provider)}${c.exact_edition?' · exact ISBN':''}</span></button>`).join('')||'<p>No artwork is cached yet. Use “Find more covers” to search the providers.</p>'}</div><form id="v14-custom-cover" class="form-stack"><div class="field"><label for="v14-cover-url">Or use an image URL</label><input class="input" id="v14-cover-url" type="url" placeholder="https://…"></div><div class="modal-actions"><button class="btn" type="button" data-v14-close>Cancel</button><button class="btn btn-primary" type="submit">Use URL</button></div></form>`);modalRoot.querySelectorAll('[data-v14-candidate]').forEach(b=>b.addEventListener('click',()=>chooseCover(book,b.dataset.v14Candidate,b)));modalRoot.querySelector('#v14-find-covers')?.addEventListener('click',async e=>{const btn=e.currentTarget;btn.disabled=true;btn.textContent='Searching…';try{const r=await invoke('cover-options',{book_id:book.id,refresh:true});renderCoverPicker(book,r.candidates||[],false)}catch(err){toast(err.message||'Could not search covers',true);btn.disabled=false;btn.textContent='Find more covers'}});modalRoot.querySelector('#v14-custom-cover')?.addEventListener('submit',async e=>{e.preventDefault();const url=e.currentTarget['v14-cover-url'].value.trim();if(!url)return;const {data,error}=await supabase.from('book_cover_candidates').upsert({book_id:book.id,edition_id:book.display_edition_id||null,provider:'Manual URL',source_label:'Custom URL',source_url:url,exact_edition:book.ownership_status==='Owned'},{onConflict:'book_id,source_url'}).select('id').single();if(error){toast(error.message,true);return}await chooseCover(book,data.id,e.currentTarget.querySelector('button[type="submit"]'))})}
async function openFastCoverPicker(id){try{const [book,candidates]=await Promise.all([getBook(id),savedCandidates(id)]);renderCoverPicker(book,candidates,false)}catch(e){toast(e.message||'Could not load saved covers',true)}}
async function chooseCover(book,candidateId,button){button.disabled=true;try{const r=await invoke('select-cover',{book_id:book.id,candidate_id:candidateId,lock:true});if(r?.cover_url)writeOverride(book.id,book.title,r.cover_url);await window.LibraryDataCache?.clear?.();modalRoot.innerHTML='';toast('Cover saved.')}catch(e){toast(e.message||'Could not save cover',true);button.disabled=false}}

async function openFastProgress(id){try{let book=await getBook(id);const o=progressOverrides()[id];if(o&&Date.now()-Number(o.savedAt||0)<24*60*60*1000)book={...book,...o};openModal(`<h2>Update progress</h2><p class="progress-book-name">${esc(book.title)}</p><form id="v14-progress-form" class="form-stack"><div class="field"><label for="v14-page">Current page</label><input class="input page-input" id="v14-page" type="number" min="0" ${book.total_pages?`max="${book.total_pages}"`:''} inputmode="numeric" value="${book.current_page??''}" autofocus required>${book.total_pages?`<small class="field-hint">${book.total_pages} pages in this edition</small>`:''}</div><div class="modal-actions"><button class="btn" type="button" data-v14-close>Cancel</button><button class="btn btn-primary" type="submit">Save progress</button></div></form>`);setTimeout(()=>modalRoot.querySelector('#v14-page')?.focus(),50);modalRoot.querySelector('#v14-progress-form')?.addEventListener('submit',async e=>{e.preventDefault();const btn=e.currentTarget.querySelector('button[type="submit"]');btn.disabled=true;try{const page=Number(e.currentTarget['v14-page'].value);const {error}=await supabase.rpc('update_reading_progress',{p_book_id:id,p_page:page,p_source:'frontend'});if(error)throw error;await window.LibraryDataCache?.clear?.();const [{data:fresh},{data:chapter}]=await Promise.all([supabase.from('v_library').select('*').eq('id',id).single(),supabase.from('v_library_chapters').select('*').eq('id',id).maybeSingle()]);if(fresh)writeProgressOverride({...fresh,...(chapter||{})});modalRoot.innerHTML='';toast('Progress updated.');refreshCurrentDetail(id)}catch(err){toast(err.message||'Could not update progress',true);btn.disabled=false}})}catch(e){toast(e.message||'Could not load reading progress',true)}}

async function openFastReview(id){try{const book=await getBook(id);openModal(`<h2>${book.user_rating_5!=null?'Edit':'Add'} your rating</h2><p>Use the stars for a quick score or type a precise X.XX rating. Notes become reading feedback for future recommendations.</p><form id="v14-review-form" class="form-stack"><div class="quick-stars">${[1,2,3,4,5].map(n=>`<button type="button" data-v14-star="${n}">★</button>`).join('')}</div><div class="field"><label for="v14-rating">Your rating / 5</label><input class="input rating-input" id="v14-rating" type="number" min="0" max="5" step="0.01" inputmode="decimal" value="${book.user_rating_5??''}" placeholder="4.25" required></div><div class="field"><label for="v14-notes">Review notes</label><textarea class="input" id="v14-notes" rows="7">${esc(book.review_notes||book.user_review||'')}</textarea></div><div class="modal-actions"><button class="btn" type="button" data-v14-close>Cancel</button><button class="btn btn-primary" type="submit">Save</button></div></form>`);const input=modalRoot.querySelector('#v14-rating');modalRoot.querySelectorAll('[data-v14-star]').forEach(b=>b.addEventListener('click',()=>{input.value=b.dataset.v14Star;modalRoot.querySelectorAll('[data-v14-star]').forEach(s=>s.classList.toggle('active',Number(s.dataset.v14Star)<=Number(b.dataset.v14Star)))}));modalRoot.querySelector('#v14-review-form')?.addEventListener('submit',async e=>{e.preventDefault();const btn=e.currentTarget.querySelector('button[type="submit"]');btn.disabled=true;try{const rating=Number(e.currentTarget['v14-rating'].value),notes=e.currentTarget['v14-notes'].value.trim()||null;const {error}=await supabase.rpc('save_book_review',{p_book_id:id,p_rating:rating,p_notes:notes,p_source:'frontend'});if(error)throw error;await window.LibraryDataCache?.clear?.();try{localStorage.removeItem('library-detail-cache-v4')}catch{}modalRoot.innerHTML='';toast(`Rating saved at ${fmtRating(rating)}/5.`);refreshCurrentDetail(id)}catch(err){toast(err.message||'Could not save rating',true);btn.disabled=false}})}catch(e){toast(e.message||'Could not load review',true)}}

async function openFastPageCount(id){try{const book=await getBook(id);const current=book.edition_page_count||book.total_pages||'';openModal(`<h2>Edit page count</h2><p>Correct the total pages for the displayed edition.</p><form id="v14-pages-form" class="form-stack"><div class="field"><label for="v14-pages">Total pages</label><input class="input rating-input" id="v14-pages" type="number" min="1" inputmode="numeric" value="${esc(current)}" required></div><div class="modal-actions"><button class="btn" type="button" data-v14-close>Cancel</button><button class="btn btn-primary" type="submit">Save pages</button></div></form>`);modalRoot.querySelector('#v14-pages-form')?.addEventListener('submit',async e=>{e.preventDefault();const btn=e.currentTarget.querySelector('button[type="submit"]');btn.disabled=true;try{const pages=Number(e.currentTarget['v14-pages'].value);const {error}=await supabase.rpc('set_book_page_count',{p_book_id:id,p_total_pages:pages,p_source:'frontend'});if(error)throw error;await window.LibraryDataCache?.clear?.();modalRoot.innerHTML='';toast('Page count updated.');refreshCurrentDetail(id)}catch(err){toast(err.message||'Could not update page count',true);btn.disabled=false}})}catch(e){toast(e.message||'Could not load page count',true)}}

document.addEventListener('click',e=>{const cover=e.target.closest('[data-v4-cover]');if(cover){e.preventDefault();e.stopImmediatePropagation();openFastCoverPicker(cover.dataset.v4Cover);return}const progress=e.target.closest('[data-progress]');if(progress){e.preventDefault();e.stopImmediatePropagation();openFastProgress(progress.dataset.progress);return}const review=e.target.closest('[data-v4-review]');if(review){e.preventDefault();e.stopImmediatePropagation();openFastReview(review.dataset.v4Review);return}const pages=e.target.closest('[data-v4-pages]');if(pages){e.preventDefault();e.stopImmediatePropagation();openFastPageCount(pages.dataset.v4Pages);return}},{capture:true});

const sleep=ms=>new Promise(r=>setTimeout(r,ms));
async function repairOne(book){if(repairedThisSession.has(book.id))return;repairedThisSession.add(book.id);try{await invoke('content-enrichment',{book_id:book.id,force:true})}catch(e){console.info(`[Library] background metadata repair skipped for ${book.title}:`,e.message)}}
async function runChunk(items){let i=0;async function worker(){while(i<items.length){const book=items[i++];await repairOne(book);await sleep(250)}}await Promise.all([worker(),worker()])}
async function backgroundRepair(){if(repairRunning||document.hidden||!navigator.onLine)return;repairRunning=true;try{const {data:{session}}=await supabase.auth.getSession();if(!session)return;const [{data:lib,error:le},{data:core,error:ce}]=await Promise.all([supabase.from('v_library').select('id,title,ownership_status,overall_status,display_edition_id,synopsis,cover_url,total_pages,edition_page_count,current_page'),supabase.from('books').select('id,metadata_status,metadata_retry_after')]);if(le||ce||!lib?.length)return;reconcileProgressOverrides(lib);const cMap=new Map((core||[]).map(x=>[x.id,x]));const now=Date.now();const todo=lib.filter(b=>{const c=cMap.get(b.id)||{};const retry=!c.metadata_retry_after||new Date(c.metadata_retry_after).getTime()<=now;const incomplete=!b.synopsis||!b.display_edition_id||!b.total_pages||!b.cover_url;return retry&&incomplete&&!repairedThisSession.has(b.id)&&c.metadata_status!=='ambiguous'});for(let n=0;n<todo.length;n+=10){if(document.hidden)break;await runChunk(todo.slice(n,n+10));await window.LibraryDataCache?.clear?.();if(n+10<todo.length)await sleep(12000)}}catch(e){console.info('[Library] background repair paused:',e.message)}finally{repairRunning=false}}

function refreshCurrentDetail(bookId){try{localStorage.removeItem('library-detail-cache-v4')}catch{}const detail=document.querySelector('.detail-header');if(!detail)return;const current=detail.dataset.bookId;if(current&&bookId&&current!==bookId)return;detail.removeAttribute('data-library-detail');delete detail.dataset.bookId;const marker=document.createComment('metadata refreshed');detail.append(marker);marker.remove()}
window.addEventListener('library-enrichment-complete',async e=>{await window.LibraryDataCache?.clear?.();refreshCurrentDetail(e.detail?.bookId||null)});

if(document.readyState==='complete')setTimeout(backgroundRepair,900);else window.addEventListener('load',()=>setTimeout(backgroundRepair,900));window.addEventListener('online',()=>setTimeout(backgroundRepair,800));document.addEventListener('visibilitychange',()=>{if(!document.hidden)setTimeout(backgroundRepair,1000)});supabase.auth.onAuthStateChange((_e,s)=>{if(s)setTimeout(backgroundRepair,1000)});

new MutationObserver(()=>requestAnimationFrame(()=>{paintOverrides();paintProgressOverrides()})).observe(document.querySelector('#app')||document.body,{childList:true,subtree:true});paintOverrides();paintProgressOverrides();
