import { createClient } from 'https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm';
import { SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY } from './supabase-config.js';

const supabase=createClient(SUPABASE_URL,SUPABASE_PUBLISHABLE_KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});
const app=document.querySelector('#app');
const modalRoot=document.querySelector('#modal-root');
const toastNode=document.querySelector('#toast');
const DETAIL_CACHE_KEY='librariangpt-detail-cache-v3';
const ENRICH_KEY='librariangpt-enrichment-v3';
const DETAIL_TTL=30*60*1000;
let busyDetail=false;
let lastScrollY=0;

const esc=(v='')=>String(v).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;');
const fmtDate=v=>v?new Intl.DateTimeFormat('en-GB',{day:'numeric',month:'short',year:'numeric'}).format(new Date(v)):'Not recorded';
const fmtRating=v=>v==null?'—':Number(v).toFixed(2);
const fmtCount=v=>v==null?'':new Intl.NumberFormat('en-GB',{notation:Number(v)>=100000?'compact':'standard',maximumFractionDigits:1}).format(Number(v));
const norm=v=>String(v||'').trim().toLowerCase();

function readJson(key,fallback={}){try{return JSON.parse(localStorage.getItem(key)||JSON.stringify(fallback));}catch{return fallback;}}
function writeJson(key,value){try{localStorage.setItem(key,JSON.stringify(value));}catch{}}
function cacheKey(title,author){return `${norm(title)}|${norm(author)}`;}
function detailCache(){return readJson(DETAIL_CACHE_KEY,{});}
function saveDetail(bundle){const all=detailCache();all[cacheKey(bundle.book.title,bundle.book.authors)]={savedAt:Date.now(),bundle};writeJson(DETAIL_CACHE_KEY,all);}
function cachedDetail(title,author){return detailCache()[cacheKey(title,author)]||null;}
function clearDataCache(){localStorage.removeItem(DETAIL_CACHE_KEY);localStorage.removeItem(ENRICH_KEY);}

function toast(message,error=false){if(!toastNode)return;toastNode.textContent=message;toastNode.className=`toast show${error?' error':''}`;clearTimeout(toastNode._v3);toastNode._v3=setTimeout(()=>toastNode.className='toast',3600);}
function modal(html){modalRoot.innerHTML=`<div class="modal-backdrop"><div class="modal">${html}</div></div>`;modalRoot.querySelectorAll('[data-v3-close]').forEach(x=>x.addEventListener('click',()=>modalRoot.innerHTML=''));modalRoot.querySelector('.modal-backdrop')?.addEventListener('click',e=>{if(e.target.classList.contains('modal-backdrop'))modalRoot.innerHTML='';});}
async function fn(name,body){const {data,error}=await supabase.functions.invoke(name,{body});if(error)throw error;if(data?.error)throw new Error(data.error);return data;}

function providerLogo(provider=''){
 const p=provider.toLowerCase();
 if(p.includes('goodreads'))return './assets/goodreads.svg';
 if(p.includes('google'))return './assets/google-books.svg';
 if(p.includes('open library'))return './assets/open-library.svg';
 return null;
}
function ratingCard(r){const logo=providerLogo(r.provider);const count=r.rating_count!=null?`${fmtCount(r.rating_count)} ratings`:'Public score';const inner=`${logo?`<img src="${logo}" alt="${esc(r.provider)} logo">`:`<span class="rating-fallback">★</span>`}<span class="rating-copy"><strong>${fmtRating(r.rating_5)}<small>/5</small></strong><span>${esc(r.provider||'Public')} · ${esc(count)}</span></span>`;return r.source_url?`<a class="rating-card" href="${esc(r.source_url)}" target="_blank" rel="noreferrer">${inner}</a>`:`<div class="rating-card">${inner}</div>`;}
function userRatingCard(book){if(book.overall_status!=='Read'&&book.user_rating_5==null)return'';return `<button class="rating-card rating-user" type="button" data-v3-review="${book.id}"><span class="rating-fallback">YOU</span><span class="rating-copy"><strong>${fmtRating(book.user_rating_5)}<small>/5</small></strong><span>Your rating · tap to edit</span></span></button>`;}
function metadataRows(book){const rows=[['ISBN',book.isbn13||book.isbn10],['Publisher',[book.publisher,book.imprint].filter(Boolean).join(' · ')],['Edition',[book.edition_year,book.edition_format].filter(Boolean).join(' · ')],['Edition statement',book.edition_statement],['Printing / impression',book.printing_impression],['Printer code / number line',book.number_line],['Pages',book.edition_page_count||book.total_pages],['Original publication',book.original_publication_year],['Language',book.language],['Country',book.country],['Series',book.series?`${book.series}${book.series_order?` #${book.series_order}`:''}`:null],['Signed',book.signed===true?'Yes':book.signed===false?'No':null],['Condition',book.condition],['Dimensions',book.physical_dimensions],['Metadata source',book.edition_metadata_source]] .filter(([,v])=>v!==null&&v!==undefined&&String(v).trim()!=='');return rows.map(([k,v])=>`<div class="metadata-row"><span>${esc(k)}</span><strong>${esc(v)}</strong></div>`).join('');}

async function fetchBundle(title,author,force=false){
 const {data:rows,error}=await supabase.from('v_library').select('*').eq('title',title);if(error||!rows?.length)throw error||new Error('Book not found');
 const book=rows.find(x=>norm(x.authors)===norm(author))||rows[0];
 let [{data:ratings},{data:rec}]=await Promise.all([
  supabase.from('public_ratings').select('provider,rating_5,rating_count,review_count,source_url,is_primary,fetched_at').eq('book_id',book.id).order('is_primary',{ascending:false}).order('fetched_at',{ascending:false}),
  supabase.from('recommendations').select('why_recommended,match_score_10,outcome,recommendation_strength').eq('book_id',book.id).order('date_recommended',{ascending:false}).limit(1).maybeSingle()
 ]);
 let needs=!book.synopsis||!(ratings||[]).length;
 const enrich=readJson(ENRICH_KEY,{});const last=Number(enrich[book.id]||0);if((needs||force)&&(force||Date.now()-last>24*60*60*1000)){
  enrich[book.id]=Date.now();writeJson(ENRICH_KEY,enrich);
  try{await fn('content-enrichment',{book_id:book.id,force});const fresh=await supabase.from('v_library').select('*').eq('id',book.id).single();if(!fresh.error&&fresh.data)Object.assign(book,fresh.data);const rr=await supabase.from('public_ratings').select('provider,rating_5,rating_count,review_count,source_url,is_primary,fetched_at').eq('book_id',book.id).order('is_primary',{ascending:false}).order('fetched_at',{ascending:false});ratings=rr.data||ratings;}catch(e){console.info('[Library] enrichment unavailable',e?.message||e);}
 }
 const bundle={book,ratings:ratings||[],rec:rec||null};saveDetail(bundle);return bundle;
}

function parseCurrentDetail(detail){return {title:detail.querySelector('.detail-copy h1')?.textContent?.trim(),author:detail.querySelector('.hero-author')?.textContent?.trim()};}
function renderDetail(detail,bundle){
 const {book,ratings,rec}=bundle;const oldCopy=detail.querySelector('.detail-copy');if(!oldCopy)return;
 const progress=oldCopy.querySelector('.progress-block');const actions=oldCopy.querySelector('.detail-actions');
 const copy=document.createElement('div');copy.className='detail-copy detail-copy-v3';
 const tags=[book.overall_status,book.ownership_status,book.primary_genre,book.edition_format].filter(Boolean);
 const publicCards=ratings.map(ratingCard).join('');
 const review=book.overall_status==='Read'?`<section class="review-panel"><div><p class="eyebrow">Your review</p><h2>${book.user_rating_5!=null?`${fmtRating(book.user_rating_5)} / 5`:'Not rated yet'}</h2><p>${esc(book.review_notes||book.user_review||'Add a few notes about what worked, what dragged, and what you would want more or less of next time. These become recommendation evidence.')}</p></div><button class="btn" data-v3-review="${book.id}">${book.user_rating_5!=null||book.review_notes?'Edit review':'Add review'}</button></section>`:'';
 copy.innerHTML=`<p class="eyebrow">${esc(book.fiction_nonfiction||'Book')}</p><h1>${esc(book.title)}</h1><div class="hero-author">${esc(book.authors||'Unknown author')}</div><div class="meta">${tags.map(t=>`<span class="badge">${esc(t)}</span>`).join('')}${rec?.match_score_10!=null?`<span class="badge accent">Predicted fit ${Number(rec.match_score_10).toFixed(1)}/10</span>`:''}</div><div class="rating-strip">${publicCards}${userRatingCard(book)}${!publicCards&&book.overall_status!=='Read'?'<div class="rating-empty">No public rating available from the connected sources yet.</div>':''}</div><section class="book-synopsis"><h2>Synopsis</h2><p>${esc(book.synopsis||'Synopsis not available yet.')}</p></section><div class="reading-slot"></div><div class="actions-slot"></div>${review}<div class="reading-dates"><div><small>Started</small><strong>${fmtDate(book.started_at)}</strong></div><div><small>Finished</small><strong>${fmtDate(book.completed_at)}</strong></div><div><small>Length</small><strong>${book.total_pages?`${esc(book.total_pages)} pages`:'Not recorded'}</strong></div></div>${rec?.why_recommended?`<section class="recommendation-panel"><p class="eyebrow">Librarian note</p><h2>Why it was recommended</h2><p>${esc(rec.why_recommended)}</p>${rec.outcome?`<span class="badge">Prediction: ${esc(rec.outcome)}</span>`:''}</section>`:''}<details class="metadata-accordion"><summary><span><strong>Book & edition details</strong><small>ISBN, publisher, printing, format and source data</small></span><span class="accordion-plus">+</span></summary><div class="metadata-list">${metadataRows(book)}<div class="metadata-row"><span>Actions</span><strong><button class="btn" data-v3-refresh-data="${book.id}">Refresh book data</button></strong></div></div></details>`;
 oldCopy.replaceWith(copy);if(progress)copy.querySelector('.reading-slot')?.append(progress);if(actions){actions.insertAdjacentHTML('beforeend',`<button class="btn" data-v3-cover="${book.id}">Edit cover</button>`);copy.querySelector('.actions-slot')?.append(actions);}detail.dataset.libraryDetail='ready';detail.dataset.bookId=book.id;
 copy.querySelectorAll('[data-v3-review]').forEach(b=>b.addEventListener('click',()=>openReview(book)));
 copy.querySelector('[data-v3-cover]')?.addEventListener('click',()=>openCoverPicker(book));
 copy.querySelector('[data-v3-refresh-data]')?.addEventListener('click',()=>refreshBookData(book));
}

async function enhanceDetail(){if(busyDetail||!app)return;const detail=app.querySelector('.detail-header');if(!detail||detail.dataset.libraryDetail==='ready'||detail.dataset.libraryDetail==='loading')return;busyDetail=true;detail.dataset.libraryDetail='loading';try{const parsed=parseCurrentDetail(detail);if(!parsed.title){delete detail.dataset.libraryDetail;return;}const cached=cachedDetail(parsed.title,parsed.author);if(cached?.bundle)renderDetail(detail,cached.bundle);if(!cached||Date.now()-Number(cached.savedAt)>DETAIL_TTL){const bundle=await fetchBundle(parsed.title,parsed.author,false);if(document.body.contains(detail))renderDetail(detail,bundle);}}catch(e){console.info('[Library] detail load failed',e?.message||e);delete detail.dataset.libraryDetail;}finally{busyDetail=false;}}

function openReview(book){modal(`<h2>${book.user_rating_5!=null?'Edit':'Add'} your review</h2><p>Your notes are saved as reading feedback and become evidence for future recommendations.</p><form id="v3-review-form" class="form-stack"><div class="field"><label for="v3-rating">Rating / 5</label><input class="input" id="v3-rating" type="number" min="0" max="5" step="0.01" inputmode="decimal" value="${book.user_rating_5??''}" placeholder="4.25" required></div><div class="field"><label for="v3-notes">Review notes</label><textarea class="input" id="v3-notes" rows="7" placeholder="What worked? What dragged? What should future recommendations learn from this?">${esc(book.review_notes||book.user_review||'')}</textarea></div><div class="modal-actions"><button class="btn btn-quiet" type="button" data-v3-close>Cancel</button><button class="btn btn-primary" type="submit">Save review</button></div></form>`);modalRoot.querySelector('#v3-review-form')?.addEventListener('submit',async e=>{e.preventDefault();const btn=e.currentTarget.querySelector('button[type="submit"]');btn.disabled=true;try{const rating=Number(e.currentTarget['v3-rating'].value);const notes=e.currentTarget['v3-notes'].value.trim()||null;const {error}=await supabase.rpc('save_book_review',{p_book_id:book.id,p_rating:rating,p_notes:notes,p_source:'frontend'});if(error)throw error;clearDataCache();modalRoot.innerHTML='';toast('Review saved.');location.reload();}catch(err){toast(err.message||'Could not save review',true);btn.disabled=false;}});}

async function openCoverPicker(book){modal(`<h2>Edit cover</h2><p>Loading available artwork for <strong>${esc(book.title)}</strong>…</p>`);try{const result=await fn('cover-options',{book_id:book.id});const candidates=result.candidates||[];modal(`<h2>Edit cover</h2><p>${book.ownership_status==='Owned'?'Exact-edition results are prioritised.':'Reference artwork is used until you own a specific edition.'} Selecting a cover stores a permanent copy in your library.</p><div class="cover-picker-grid">${candidates.map(c=>`<button class="cover-option ${c.selected?'selected':''}" data-v3-cover-option="${c.id}"><img src="${esc(c.source_url)}" alt="${esc(c.provider)} cover" loading="lazy" onerror="this.closest('button').style.display='none'"><span>${esc(c.provider)}${c.exact_edition?' · exact ISBN':''}</span></button>`).join('')||'<p>No cover options were returned.</p>'}</div><form id="v3-custom-cover" class="form-stack"><div class="field"><label for="v3-cover-url">Or use an image URL</label><input class="input" id="v3-cover-url" type="url" placeholder="https://…"></div><div class="modal-actions"><button class="btn btn-quiet" type="button" data-v3-close>Cancel</button><button class="btn" type="submit">Use URL</button></div></form>`);modalRoot.querySelectorAll('[data-v3-cover-option]').forEach(btn=>btn.addEventListener('click',()=>chooseCover(book,btn.dataset.v3CoverOption,btn)));modalRoot.querySelector('#v3-custom-cover')?.addEventListener('submit',async e=>{e.preventDefault();const url=e.currentTarget['v3-cover-url'].value.trim();if(!url)return;const row={book_id:book.id,edition_id:book.display_edition_id||null,provider:'Manual URL',source_label:'Custom URL',source_url:url,exact_edition:book.ownership_status==='Owned'};const {data,error}=await supabase.from('book_cover_candidates').upsert(row,{onConflict:'book_id,source_url'}).select('id').single();if(error){toast(error.message,true);return;}await chooseCover(book,data.id,e.currentTarget.querySelector('button[type="submit"]'));});}catch(e){toast(e.message||'Could not load cover options',true);modalRoot.innerHTML='';}}
async function chooseCover(book,candidateId,button){button.disabled=true;try{const result=await fn('select-cover',{book_id:book.id,candidate_id:candidateId});clearDataCache();modalRoot.innerHTML='';toast('Cover saved to your library.');location.reload();}catch(e){toast(e.message||'Could not save cover',true);button.disabled=false;}}

async function refreshBookData(book){const btn=document.querySelector(`[data-v3-refresh-data="${book.id}"]`);if(btn){btn.disabled=true;btn.textContent='Refreshing…';}try{await fn('content-enrichment',{book_id:book.id,force:true});clearDataCache();toast('Book data refreshed.');location.reload();}catch(e){toast(e.message||'Could not refresh book data',true);if(btn){btn.disabled=false;btn.textContent='Refresh book data';}}}

function openAddByIsbn(){modal(`<h2>Add book by ISBN</h2><p>Use the ISBN from a physical copy for an exact owned edition, or add a specific edition to your wishlist.</p><form id="v3-add-isbn" class="form-stack"><div class="field"><label for="v3-isbn">ISBN-10 or ISBN-13</label><input class="input" id="v3-isbn" autocomplete="off" required></div><div class="field"><label for="v3-add-state">Add as</label><select class="input" id="v3-add-state"><option value="wishlist">Wishlist</option><option value="owned">Owned · unread</option></select></div><div class="modal-actions"><button class="btn btn-quiet" type="button" data-v3-close>Cancel</button><button class="btn btn-primary" type="submit">Add book</button></div></form>`);modalRoot.querySelector('#v3-add-isbn')?.addEventListener('submit',async e=>{e.preventDefault();const btn=e.currentTarget.querySelector('button[type="submit"]');btn.disabled=true;try{const isbn=e.currentTarget['v3-isbn'].value.trim();const owned=e.currentTarget['v3-add-state'].value==='owned';await fn('book-metadata',{isbn,owned,set_preferred:owned,overall_status:owned?'Owned - Unread':'Wishlist'});clearDataCache();modalRoot.innerHTML='';toast('Book added.');location.reload();}catch(err){toast(err.message||'Could not add book',true);btn.disabled=false;}});}

function applyToolbar(){const toolbar=app?.querySelector('.toolbar');if(!toolbar||toolbar.dataset.v3Toolbar)return;toolbar.dataset.v3Toolbar='1';const b=document.createElement('button');b.className='btn btn-primary';b.type='button';b.textContent='Add by ISBN';b.addEventListener('click',openAddByIsbn);toolbar.prepend(b);}
function applyHeader(){const word=app?.querySelector('.wordmark span');if(word&&word.textContent!=='Library')word.textContent='Library';const old=app?.querySelector('#signout');if(old){const b=document.createElement('button');b.className='icon-btn';b.id='menu-toggle';b.setAttribute('aria-label','Menu');b.innerHTML='<span class="menu-bars"><i></i><i></i><i></i></span>';old.replaceWith(b);b.addEventListener('click',openSidebar);}}
function openSidebar(){const existing=document.querySelector('.sidebar-backdrop');if(existing){existing.remove();return;}const wrap=document.createElement('div');wrap.className='sidebar-backdrop';wrap.innerHTML=`<aside class="sidebar-panel"><div class="sidebar-head"><h2>Library</h2><button class="icon-btn" data-sidebar-close>×</button></div><section class="sidebar-section"><h3>Settings</h3><div class="setting-row"><span>Appearance</span><strong>Dark</strong></div><div class="setting-row"><span>Cover art</span><strong>Exact editions preferred</strong></div><div class="setting-row"><span>Book data cache</span><strong>30 minutes</strong></div><div class="setting-row"><span>Cover cache</span><strong>Persistent</strong></div></section><section class="sidebar-section"><h3>Library tools</h3><div class="sidebar-actions"><button class="btn" data-sidebar-add>Add book by ISBN</button><button class="btn" data-sidebar-refresh>Refresh library data</button><button class="btn" data-sidebar-clear>Clear local cache</button></div></section><section class="sidebar-section"><div class="sidebar-actions"><button class="btn btn-danger" data-sidebar-logout>Log out</button></div></section></aside>`;document.body.append(wrap);wrap.addEventListener('click',e=>{if(e.target===wrap||e.target.closest('[data-sidebar-close]'))wrap.remove();});wrap.querySelector('[data-sidebar-add]')?.addEventListener('click',()=>{wrap.remove();openAddByIsbn();});wrap.querySelector('[data-sidebar-refresh]')?.addEventListener('click',()=>{clearDataCache();location.reload();});wrap.querySelector('[data-sidebar-clear]')?.addEventListener('click',async()=>{clearDataCache();try{for(const key of await caches.keys())if(key.startsWith('librariangpt-'))await caches.delete(key);}catch{}toast('Local cache cleared.');});wrap.querySelector('[data-sidebar-logout]')?.addEventListener('click',()=>supabase.auth.signOut());}
function applyNavCompact(){const nav=app?.querySelector('.bottom-nav');if(!nav)return;nav.classList.toggle('compact',window.scrollY>100);}
function applyAll(){applyHeader();applyToolbar();enhanceDetail();applyNavCompact();}

if(app){new MutationObserver(()=>requestAnimationFrame(applyAll)).observe(app,{childList:true,subtree:true});applyAll();}
window.addEventListener('scroll',()=>{const y=window.scrollY;if(Math.abs(y-lastScrollY)>4){applyNavCompact();lastScrollY=y;}},{passive:true});
document.addEventListener('click',e=>{if(e.target.closest('#refresh')){e.preventDefault();e.stopImmediatePropagation();clearDataCache();location.reload();}},{capture:true});
