import { createClient } from 'https://esm.sh/@supabase/supabase-js@2.57.4';
const CORS={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'authorization, x-client-info, apikey, content-type','Access-Control-Allow-Methods':'POST, OPTIONS'};
const json=(b:unknown,s=200)=>new Response(JSON.stringify(b),{status:s,headers:{...CORS,'Content-Type':'application/json'}});
function extFor(t:string){if(t.includes('png'))return'png';if(t.includes('webp'))return'webp';return'jpg'}
Deno.serve(async(req:Request)=>{if(req.method==='OPTIONS')return new Response('ok',{headers:CORS});if(req.method!=='POST')return json({error:'POST required'},405);try{
 const auth=req.headers.get('Authorization');if(!auth)return json({error:'Authentication required'},401);const url=Deno.env.get('SUPABASE_URL')!,anon=Deno.env.get('SUPABASE_ANON_KEY')!,service=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;const user=createClient(url,anon,{global:{headers:{Authorization:auth}}});const ud=await user.auth.getUser();if(ud.error||!ud.data.user)return json({error:'Invalid session'},401);const own=await user.rpc('is_library_owner');if(own.error||own.data!==true)return json({error:'Not authorized'},403);
 const body=await req.json();const bookId=String(body?.book_id||''),candidateId=String(body?.candidate_id||'');const lock=body?.lock!==false;if(!bookId||!candidateId)return json({error:'book_id and candidate_id required'},400);const admin=createClient(url,service);const c=await admin.from('book_cover_candidates').select('*').eq('id',candidateId).eq('book_id',bookId).single();if(c.error||!c.data)return json({error:'Cover option not found'},404);
 const r=await fetch(c.data.source_url,{redirect:'follow',headers:{'User-Agent':'LibrarianGPT/1.3 cover selection','Accept':'image/*,*/*;q=0.8'}});const type=r.headers.get('content-type')||'';if(!r.ok||!type.startsWith('image/'))return json({error:'Selected cover is no longer available'},422);const bytes=new Uint8Array(await r.arrayBuffer());if(bytes.byteLength<1000)return json({error:'Selected cover response was not a usable image'},422);
 const lib=await admin.from('library_entries').select('ownership_status,current_edition_id').eq('book_id',bookId).single();if(lib.error||!lib.data)return json({error:'Library record not found'},404);const targetEdition=lib.data.current_edition_id||c.data.edition_id||null;const suffix=lock?'manual':'auto';const path=`${bookId}/${targetEdition||'book'}-${suffix}.${extFor(type)}`;const up=await admin.storage.from('book-covers').upload(path,bytes,{contentType:type,upsert:true,cacheControl:'31536000'});if(up.error)throw up.error;const stable=admin.storage.from('book-covers').getPublicUrl(path).data.publicUrl;
 await admin.from('book_cover_candidates').update({selected:false,updated_at:new Date().toISOString()}).eq('book_id',bookId);await admin.from('book_cover_candidates').update({selected:true,updated_at:new Date().toISOString()}).eq('id',candidateId);
 if(targetEdition){await admin.from('editions').update({cover_url:stable,cover_source:`${lock?'Manual':'Automatic'} · ${c.data.provider}`,cover_verified:true,cover_locked:lock}).eq('id',targetEdition)}
 await admin.from('books').update({cover_url_preferred:stable,cover_source:`${lock?'Manual':'Automatic'} · ${c.data.provider}`,cover_verified:true,cover_locked:lock}).eq('id',bookId);
 await admin.from('library_events').insert({user_id:ud.data.user.id,book_id:bookId,event_type:lock?'cover_selected':'cover_auto_selected',source:lock?'frontend':'cover_queue',payload:{candidate_id:candidateId,provider:c.data.provider,source_url:c.data.source_url,stored_url:stable,locked:lock}});
 return json({ok:true,cover_url:stable,provider:c.data.provider,locked:lock});
}catch(e){console.error(e);return json({error:e?.message||'Could not save cover'},500)}});
