import { fetchCoverImage } from '../_shared/cover-fetch.js';
import { createClient } from 'https://esm.sh/@supabase/supabase-js@2.57.4';
const CORS={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'authorization, x-client-info, apikey, content-type','Access-Control-Allow-Methods':'POST, OPTIONS'};
const json=(b:unknown,s=200)=>new Response(JSON.stringify(b),{status:s,headers:{...CORS,'Content-Type':'application/json'}});
function extFor(t:string){if(t.includes('png'))return'png';if(t.includes('webp'))return'webp';return'jpg'}
Deno.serve(async(req:Request)=>{if(req.method==='OPTIONS')return new Response('ok',{headers:CORS});if(req.method!=='POST')return json({error:'POST required'},405);try{
 const auth=req.headers.get('Authorization');if(!auth)return json({error:'Authentication required'},401);const url=Deno.env.get('SUPABASE_URL')!,anon=Deno.env.get('SUPABASE_ANON_KEY')!,service=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;const user=createClient(url,anon,{global:{headers:{Authorization:auth}}});const ud=await user.auth.getUser();if(ud.error||!ud.data.user)return json({error:'Invalid session'},401);const own=await user.rpc('is_library_owner');if(own.error||own.data!==true)return json({error:'Not authorized'},403);
 const body=await req.json();const bookId=String(body?.book_id||''),candidateId=String(body?.candidate_id||'');const lock=body?.lock!==false;if(!bookId||!candidateId)return json({error:'book_id and candidate_id required'},400);const admin=createClient(url,service);const c=await admin.from('book_cover_candidates').select('*').eq('id',candidateId).eq('book_id',bookId).single();if(c.error||!c.data)return json({error:'Cover option not found'},404);
 const image=await fetchCoverImage(c.data.source_url);const bytes=image.bytes,type=image.mime;
 const lib=await admin.from('library_entries').select('ownership_status,current_edition_id').eq('book_id',bookId).eq('user_id',ud.data.user.id).single();if(lib.error||!lib.data)return json({error:'Library record not found'},404);const targetEdition=lib.data.current_edition_id||c.data.edition_id||null;const suffix=lock?'manual':'auto';const path=`${bookId}/${targetEdition||'book'}-${suffix}-${crypto.randomUUID()}.${extFor(type)}`;const up=await admin.storage.from('book-covers').upload(path,bytes,{contentType:type,upsert:true,cacheControl:'31536000'});if(up.error)throw up.error;const stable=admin.storage.from('book-covers').getPublicUrl(path).data.publicUrl;
 const saved=await admin.rpc('save_cover_selection',{p_user_id:ud.data.user.id,p_book_id:bookId,p_edition_id:targetEdition,p_url:stable,p_provider:c.data.provider,p_label:c.data.source_label||'Selected cover',p_uploaded:false,p_lock:lock});
 if(saved.error){await admin.storage.from('book-covers').remove([path]);throw saved.error;}
 return json({ok:true,cover_url:stable,provider:c.data.provider,locked:lock});
}catch(e){console.error(e);return json({error:e?.message||'Could not save cover'},500)}});
