import { createClient } from 'https://esm.sh/@supabase/supabase-js@2.57.4';

const CORS={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'authorization, x-client-info, apikey, content-type','Access-Control-Allow-Methods':'POST, OPTIONS'};
const json=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:{...CORS,'Content-Type':'application/json'}});
const cleanIsbn=(v:unknown)=>String(v??'').replace(/[^0-9Xx]/g,'').toUpperCase();
function valid(i:string){if(/^\d{13}$/.test(i)){const s=i.slice(0,12).split('').reduce((a,c,n)=>a+Number(c)*(n%2?3:1),0);return(10-s%10)%10===Number(i[12])}if(/^\d{9}[\dX]$/.test(i)){let s=0;for(let n=0;n<10;n++)s+=(i[n]==='X'?10:Number(i[n]))*(10-n);return s%11===0}return false}
const norm=(v?:string|null)=>String(v??'').toLowerCase().normalize('NFKD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9 ]/g,' ').replace(/\s+/g,' ').trim().replace(/^(the|a|an)\s+/,'');
function sim(a?:string|null,b?:string|null){const aa=norm(a),bb=norm(b);if(!aa||!bb)return 0;if(aa===bb)return 1;if(aa.includes(bb)||bb.includes(aa))return .96;const A=new Set(aa.split(' ').filter(x=>x.length>1)),B=new Set(bb.split(' ').filter(x=>x.length>1));if(!A.size||!B.size)return 0;return[...A].filter(x=>B.has(x)).length/Math.max(A.size,B.size)}
function authorSim(target:string,cands:string[]){if(!target)return .78;let best=0;for(const c of cands){best=Math.max(best,sim(target,c));const a=norm(target).split(' ').at(-1),b=norm(c).split(' ').at(-1);if(a&&b&&a===b)best=Math.max(best,.92)}return best}
async function fj(url:string,timeout=8500){const c=new AbortController(),t=setTimeout(()=>c.abort(),timeout);try{const r=await fetch(url,{signal:c.signal,redirect:'follow',headers:{'User-Agent':'ReadingRoom/8.0 (personal library catalogue)','Accept':'application/json,text/html;q=0.9,*/*;q=0.8'}});if(!r.ok)return null;const ct=r.headers.get('content-type')||'';if(ct.includes('json'))return await r.json();return await r.text()}catch{return null}finally{clearTimeout(t)}}
const gid=(v:any,t:string)=>v?.industryIdentifiers?.find((x:any)=>x?.type===t)?.identifier??null;
const yr=(v:any)=>{const m=String(v??'').match(/(?:^|\D)(1[0-9]{3}|20[0-9]{2}|2100)(?:\D|$)/);return m?Number(m[1]):null};
const gcover=(v:any)=>{const l=v?.imageLinks||{};return[l.extraLarge,l.large,l.medium,l.small,l.thumbnail,l.smallThumbnail].find(Boolean)?.replace(/^http:/,'https:')||null};
const text=(v:any)=>{const s=String(typeof v==='string'?v:v?.value??'').replace(/<[^>]+>/g,' ').replace(/\s+/g,' ').trim();return s?(s.length>3000?s.slice(0,2997)+'…':s):null};
const meta=(html:string,name:string)=>{const esc=name.replace(/[.*+?^${}()|[\]\\]/g,'\\$&');const rx=new RegExp(`<meta[^>]+(?:name|property)=["']${esc}["'][^>]+content=["']([^"']+)["'][^>]*>|<meta[^>]+content=["']([^"']+)["'][^>]+(?:name|property)=["']${esc}["'][^>]*>`,'i');const m=html.match(rx);return m?(m[1]||m[2]||'').replace(/&amp;/g,'&').replace(/&quot;/g,'"').replace(/&#39;/g,"'"):null};

type R={title:string,subtitle?:string|null,authors:string[],isbn10:string|null,isbn13:string|null,publisher:string|null,publication_year:number|null,page_count:number|null,format:string|null,cover_url:string|null,synopsis?:string|null,primary_genre?:string|null,language?:string|null,open_library_work_id?:string|null,provider:string,provider_id:string|null,score:number,existing_book_id?:string|null,already_in_library?:boolean};
function googleResult(item:any,q:string,author:string,isIsbn=false):R|null{const v=item?.volumeInfo||{},i13=cleanIsbn(gid(v,'ISBN_13')),i10=cleanIsbn(gid(v,'ISBN_10'));const isbn13=valid(i13)?i13:null,isbn10=valid(i10)?i10:null;if(!isbn13&&!isbn10)return null;const title=String(v.title||'').trim();if(!title)return null;const authors=Array.isArray(v.authors)?v.authors.filter(Boolean):[];const ts=isIsbn?1:sim(q,title),as=author?authorSim(author,authors):.8;if(!isIsbn&&(ts<.34||(author&&as<.28)))return null;return{title,subtitle:v.subtitle||null,authors,isbn10,isbn13,publisher:v.publisher||null,publication_year:yr(v.publishedDate),page_count:Number(v.pageCount)||null,format:v.printType||null,cover_url:gcover(v),synopsis:text(v.description),primary_genre:Array.isArray(v.categories)?v.categories[0]||null:null,language:v.language||null,provider:'Google Books',provider_id:item.id||null,score:ts*.76+as*.24+.04}}
function olResult(e:any,authors:string[],base:number,workId:string|null,synopsis:string|null):R|null{const i13=(Array.isArray(e?.isbn_13)?e.isbn_13:[]).map(cleanIsbn).find((x:string)=>valid(x)&&x.length===13)||null,i10=(Array.isArray(e?.isbn_10)?e.isbn_10:[]).map(cleanIsbn).find((x:string)=>valid(x)&&x.length===10)||null;if(!i13&&!i10)return null;const title=String(e?.title||'').trim();if(!title)return null;const covers=Array.isArray(e?.covers)?e.covers:[],key=String(e?.key||'').replace('/books/','')||null,pubs=Array.isArray(e?.publishers)?e.publishers:[];return{title,subtitle:e?.subtitle||null,authors,isbn10:i10,isbn13:i13,publisher:typeof pubs[0]==='string'?pubs[0]:pubs[0]?.name||null,publication_year:yr(e?.publish_date),page_count:Number(e?.number_of_pages)||null,format:e?.physical_format||null,cover_url:covers[0]?`https://covers.openlibrary.org/b/id/${covers[0]}-L.jpg?default=false`:null,synopsis,language:null,open_library_work_id:workId,provider:'Open Library',provider_id:key,score:base}}
function crossrefResult(item:any,q:string,author:string):R|null{const titles=Array.isArray(item?.title)?item.title:[],title=String(titles[0]||'').trim();if(!title)return null;const authors=(Array.isArray(item?.author)?item.author:[]).map((a:any)=>[a.given,a.family].filter(Boolean).join(' ').trim()).filter(Boolean);const ts=sim(q,title),as=author?authorSim(author,authors):.8;if(ts<.34||(author&&as<.28))return null;const ids=(Array.isArray(item?.ISBN)?item.ISBN:[]).map(cleanIsbn).filter(valid);const isbn13=ids.find((x:string)=>x.length===13)||null,isbn10=ids.find((x:string)=>x.length===10)||null;if(!isbn13&&!isbn10)return null;const dp=item?.published?.['date-parts']?.[0]||item?.['published-print']?.['date-parts']?.[0]||item?.['published-online']?.['date-parts']?.[0]||[];const pages=String(item?.page||'').match(/^(\d+)(?:\D|$)/);return{title,subtitle:Array.isArray(item?.subtitle)?item.subtitle[0]||null:null,authors,isbn10,isbn13,publisher:item?.publisher||null,publication_year:Number(dp?.[0])||null,page_count:pages?Number(pages[1]):null,format:'Book',cover_url:null,synopsis:text(item?.abstract),primary_genre:'Book',language:item?.language||null,provider:'Crossref',provider_id:item?.DOI||null,score:ts*.76+as*.24+.025}}
function addUnique(out:R[],r:R|null){if(!r)return;const k=r.isbn13||r.isbn10||`${norm(r.title)}|${norm(r.authors[0]||'')}`;const i=out.findIndex(x=>(x.isbn13||x.isbn10||`${norm(x.title)}|${norm(x.authors[0]||'')}`)===k);if(i<0)out.push(r);else{const old=out[i];const better=r.score>old.score?r:old;out[i]={...old,...better,cover_url:old.cover_url||r.cover_url,synopsis:old.synopsis||r.synopsis,page_count:old.page_count||r.page_count,publisher:old.publisher||r.publisher}}}
function googleUrl(query:string,key:string|null){const u=new URL('https://www.googleapis.com/books/v1/volumes');u.searchParams.set('q',query);u.searchParams.set('maxResults','40');u.searchParams.set('projection','full');if(key)u.searchParams.set('key',key);return u.toString()}
async function googleQuery(query:string,key:string|null){let d=await fj(googleUrl(query,key),8500);if((!d||!Array.isArray((d as any)?.items)||!(d as any).items.length)&&key)d=await fj(googleUrl(query,null),8500);return d}
async function crossrefSearch(q:string,author:string){const u=new URL('https://api.crossref.org/works');u.searchParams.set('query.bibliographic',[q,author].filter(Boolean).join(' '));u.searchParams.set('filter','type:book');u.searchParams.set('rows','20');u.searchParams.set('select','DOI,title,subtitle,author,ISBN,publisher,published,published-print,published-online,page,abstract,language,type,URL');return fj(u.toString(),9000)}
async function enrichCrossref(r:R){if(r.provider!=='Crossref'||!r.provider_id)return r;const target=`https://doi.org/${encodeURIComponent(r.provider_id)}`;const html=await fj(target,6000);if(typeof html!=='string')return r;const cover=meta(html,'og:image')||meta(html,'twitter:image');const synopsis=meta(html,'description')||meta(html,'og:description');return{...r,cover_url:r.cover_url||cover,synopsis:r.synopsis||text(synopsis)}}

Deno.serve(async(req:Request)=>{if(req.method==='OPTIONS')return new Response('ok',{headers:CORS});if(req.method!=='POST')return json({error:'POST required'},405);try{
 const su=Deno.env.get('SUPABASE_URL')!,ak=Deno.env.get('SUPABASE_ANON_KEY')!,sk=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!,auth=req.headers.get('Authorization');if(!auth)return json({error:'Authentication required'},401);const uc=createClient(su,ak,{global:{headers:{Authorization:auth}}});const ud=await uc.auth.getUser();if(ud.error||!ud.data.user)return json({error:'Invalid session'},401);const own=await uc.rpc('is_library_owner');if(own.error||own.data!==true)return json({error:'Not authorized'},403);const admin=createClient(su,sk);
 const body=await req.json(),q=String(body?.query||'').trim(),author=String(body?.author||'').trim();if(!q)return json({error:'Enter a title or ISBN.'},400);const cq=cleanIsbn(q),isIsbn=valid(cq),out:R[]=[];const diagnostics:any={};
 if(!isIsbn){const x=await admin.from('v_library').select('id,title,subtitle,authors,isbn10,isbn13,publisher,edition_year,total_pages,edition_format,cover_url,synopsis,primary_genre,language,overall_status').ilike('title',`%${q}%`).limit(15);for(const b of x.data||[]){const names=String(b.authors||'').split(',').map((s:string)=>s.trim()).filter(Boolean),ts=sim(q,b.title),as=author?authorSim(author,names):.8;if(ts<.5||(author&&as<.38))continue;addUnique(out,{title:b.title,subtitle:b.subtitle,authors:names,isbn10:b.isbn10||null,isbn13:b.isbn13||null,publisher:b.publisher||null,publication_year:b.edition_year||null,page_count:b.total_pages||null,format:b.edition_format||null,cover_url:b.cover_url||null,synopsis:b.synopsis||null,primary_genre:b.primary_genre||null,language:b.language||null,provider:'Reading Room',provider_id:b.id,score:1.2,existing_book_id:b.id,already_in_library:true})}}
 const key=Deno.env.get('GOOGLE_BOOKS_API_KEY')||null;let googlePayloads:any[]=[],olSearch:any=null,crossRaw:any=null;
 if(isIsbn){const [g,o]=await Promise.all([googleQuery(`isbn:${cq}`,key),fj(`https://openlibrary.org/isbn/${encodeURIComponent(cq)}.json`,7500)]);googlePayloads=[g];diagnostics.google=Array.isArray((g as any)?.items)?(g as any).items.length:0;if(o){let authors:string[]=[];for(const a of(Array.isArray((o as any).authors)?(o as any).authors.slice(0,3):[])){if(a?.key){const ad=await fj(`https://openlibrary.org${a.key}.json`,3500);if((ad as any)?.name)authors.push((ad as any).name)}}const w=String((o as any)?.works?.[0]?.key||'').match(/\/works\/(OL\d+W)/)?.[1]||null;let syn:string|null=null;if(w){const wd=await fj(`https://openlibrary.org/works/${w}.json`,4000);syn=text((wd as any)?.description)}addUnique(out,olResult(o,authors,1,w,syn))}}
 else{
   const queries=[`intitle:${q}${author?` inauthor:${author}`:''}`,`"${q}"${author?` "${author}"`:''}`,`${q}${author?` ${author}`:''}`];
   const ou=new URL('https://openlibrary.org/search.json');ou.searchParams.set('title',q);if(author)ou.searchParams.set('author',author);ou.searchParams.set('limit','8');ou.searchParams.set('fields','key,title,author_name,edition_key,first_publish_year');
   const settled=await Promise.all([...queries.map(x=>googleQuery(x,key)),fj(ou.toString(),7500),crossrefSearch(q,author)]);googlePayloads=settled.slice(0,3);olSearch=settled[3];crossRaw=settled[4];diagnostics.google=googlePayloads.reduce((n,g)=>n+(Array.isArray((g as any)?.items)?(g as any).items.length:0),0);diagnostics.open_library=Array.isArray((olSearch as any)?.docs)?(olSearch as any).docs.length:0;diagnostics.crossref=Array.isArray((crossRaw as any)?.message?.items)?(crossRaw as any).message.items.length:0;
 }
 for(const g of googlePayloads)for(const item of(Array.isArray((g as any)?.items)?(g as any).items:[]))addUnique(out,googleResult(item,q,author,isIsbn));
 if(!isIsbn&&crossRaw){for(const item of(Array.isArray((crossRaw as any)?.message?.items)?(crossRaw as any).message.items:[]))addUnique(out,crossrefResult(item,q,author))}
 if(!isIsbn&&olSearch){const docs=(Array.isArray((olSearch as any)?.docs)?(olSearch as any).docs:[]).map((d:any)=>({d,ts:sim(q,d?.title),as:author?authorSim(author,Array.isArray(d?.author_name)?d.author_name:[]):.8})).filter((x:any)=>x.ts>=.38&&(!author||x.as>=.3)).sort((a:any,b:any)=>(b.ts*.76+b.as*.24)-(a.ts*.76+a.as*.24)).slice(0,4);const workDescriptions=new Map<string,string|null>();await Promise.all(docs.slice(0,3).map(async({d}:any)=>{const w=String(d.key||'').match(/\/works\/(OL\d+W)/)?.[1]||null;if(!w)return;const wd=await fj(`https://openlibrary.org/works/${w}.json`,4000);workDescriptions.set(w,text((wd as any)?.description))}));const jobs:any[]=[];for(const {d,ts,as} of docs){const authors=Array.isArray(d.author_name)?d.author_name.filter(Boolean):[],workId=String(d.key||'').match(/\/works\/(OL\d+W)/)?.[1]||null,base=ts*.76+as*.24;for(const ed of(Array.isArray(d.edition_key)?d.edition_key:[]).slice(0,5))jobs.push({ed,authors,workId,base})}const editions=await Promise.all(jobs.slice(0,14).map(async j=>({j,e:await fj(`https://openlibrary.org/books/${j.ed}.json`,5000)})));for(const {j,e} of editions)if(e)addUnique(out,olResult(e,j.authors,j.base,j.workId,j.workId?workDescriptions.get(j.workId)||null:null))}
 const crossTop=out.filter(x=>x.provider==='Crossref'&&x.score>=.7).sort((a,b)=>b.score-a.score).slice(0,3);if(crossTop.length){const richer=await Promise.all(crossTop.map(enrichCrossref));for(const r of richer)addUnique(out,r)}
 let list=out.sort((a,b)=>b.score-a.score+Number(Boolean(b.cover_url))*.01-Number(Boolean(a.cover_url))*.01).slice(0,20);
 const unresolved=list.filter(x=>!x.existing_book_id),i13=unresolved.map(x=>x.isbn13).filter(Boolean) as string[],i10=unresolved.map(x=>x.isbn10).filter(Boolean) as string[];const [c13,c10]=await Promise.all([i13.length?admin.from('editions').select('book_id,isbn13,isbn10').in('isbn13',i13):Promise.resolve({data:[]}),i10.length?admin.from('editions').select('book_id,isbn13,isbn10').in('isbn10',i10):Promise.resolve({data:[]})]);const ex=[...(c13.data||[]),...(c10.data||[])],bids=[...new Set(ex.map((e:any)=>e.book_id))];let lib=new Set<string>();if(bids.length){const l=await admin.from('library_entries').select('book_id').eq('user_id',ud.data.user.id).in('book_id',bids);lib=new Set((l.data||[]).map((x:any)=>x.book_id))}list=list.map(r=>{if(r.existing_book_id)return r;const e=ex.find((x:any)=>(r.isbn13&&x.isbn13===r.isbn13)||(r.isbn10&&x.isbn10===r.isbn10));return{...r,existing_book_id:e?.book_id||null,already_in_library:e?lib.has(e.book_id):false}});
 return json({ok:true,query:q,results:list,diagnostics});
}catch(e){console.error(e);return json({error:(e as any)?.message||'Book search failed.'},500)}});
