import { createClient } from 'https://esm.sh/@supabase/supabase-js@2.57.4';
const CORS={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'authorization, x-client-info, apikey, content-type','Access-Control-Allow-Methods':'POST, OPTIONS'};
const json=(b:unknown,s=200)=>new Response(JSON.stringify(b),{status:s,headers:{...CORS,'Content-Type':'application/json'}});
const clean=(v:any)=>String(v??'').replace(/<[^>]+>/g,' ').replace(/\s+/g,' ').trim();
const norm=(v:any)=>clean(v).toLowerCase().normalize('NFKD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9 ]/g,' ').replace(/\s+/g,' ').trim().replace(/^(the|a|an)\s+/,'');
const isbn=(v:any)=>String(v??'').replace(/[^0-9Xx]/g,'').toUpperCase();
const year=(v:any)=>{const m=String(v??'').match(/(?:^|\D)(1[0-9]{3}|20[0-9]{2}|2100)(?:\D|$)/);return m?Number(m[1]):null};
function valid(i:string){if(/^\d{13}$/.test(i)){const s=i.slice(0,12).split('').reduce((a,c,n)=>a+Number(c)*(n%2?3:1),0);return(10-s%10)%10===Number(i[12])}if(/^\d{9}[\dX]$/.test(i)){let s=0;for(let n=0;n<10;n++)s+=(i[n]==='X'?10:Number(i[n]))*(10-n);return s%11===0}return false}
function sim(a:any,b:any){const A=norm(a),B=norm(b);if(!A||!B)return 0;if(A===B)return 1;if(A.includes(B)||B.includes(A))return .96;const as=new Set(A.split(' ').filter((x:string)=>x.length>1)),bs=new Set(B.split(' ').filter((x:string)=>x.length>1));return[...as].filter(x=>bs.has(x)).length/Math.max(as.size,bs.size)}
function authorSim(target:any,cands:any[]=[]){if(!target)return .75;let best=0;for(const c of cands){best=Math.max(best,sim(target,c));const a=norm(target).split(' ').at(-1),b=norm(c).split(' ').at(-1);if(a&&b&&a===b)best=Math.max(best,.92)}return best}
async function fj(url:string,ms=9000){const c=new AbortController(),t=setTimeout(()=>c.abort(),ms);try{const r=await fetch(url,{signal:c.signal,headers:{'User-Agent':'ReadingRoom/6.0 edition browser'}});if(!r.ok)return null;return await r.json()}catch{return null}finally{clearTimeout(t)}}
const gcover=(v:any)=>{const l=v?.imageLinks||{};return[l.extraLarge,l.large,l.medium,l.small,l.thumbnail,l.smallThumbnail].find(Boolean)?.replace(/^http:/,'https:')||null};
const gid=(v:any,t:string)=>v?.industryIdentifiers?.find((x:any)=>x?.type===t)?.identifier??null;
function fmt(v:any){const s=clean(v).toLowerCase();if(/hardcover|hardback/.test(s))return'Hardcover';if(/paperback|softcover|mass market/.test(s))return'Paperback';if(/kindle|ebook|e-book|electronic/.test(s))return'eBook';if(/audio/.test(s))return'Audiobook';return clean(v)||null}
function lang(v:any){const s=String(v??'').toLowerCase();const m:any={en:'English',eng:'English',fr:'French',fre:'French',fra:'French',de:'German',ger:'German',deu:'German',es:'Spanish',spa:'Spanish',it:'Italian',ita:'Italian'};return m[s]||clean(v)||null}
function olCover(e:any){const id=Array.isArray(e?.covers)?e.covers.find((x:any)=>Number(x)>0):null;return id?`https://covers.openlibrary.org/b/id/${id}-L.jpg?default=false`:null}
function same(a:any,b:any){return Boolean((a.isbn13&&b.isbn13===a.isbn13)||(a.isbn10&&b.isbn10===a.isbn10)||(a.open_library_edition_id&&b.open_library_edition_id===a.open_library_edition_id)||(a.google_books_volume_id&&b.google_books_volume_id===a.google_books_volume_id))}

Deno.serve(async(req:Request)=>{if(req.method==='OPTIONS')return new Response('ok',{headers:CORS});if(req.method!=='POST')return json({error:'POST required'},405);let admin:any,bookId='';try{
 const auth=req.headers.get('Authorization');if(!auth)return json({error:'Authentication required'},401);const url=Deno.env.get('SUPABASE_URL')!,anon=Deno.env.get('SUPABASE_ANON_KEY')!,service=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;const user=createClient(url,anon,{global:{headers:{Authorization:auth}}});const ud=await user.auth.getUser();if(ud.error||!ud.data.user)return json({error:'Invalid session'},401);const own=await user.rpc('is_library_owner');if(own.error||own.data!==true)return json({error:'Not authorized'},403);admin=createClient(url,service);
 const body=await req.json();bookId=String(body?.book_id||'');const force=body?.force===true;if(!bookId)return json({error:'book_id required'},400);const bq=await admin.from('v_library').select('*').eq('id',bookId).single();if(bq.error||!bq.data)return json({error:'Book not found'},404);const book=bq.data;const sq=await admin.from('books').select('editions_status,editions_last_refreshed_at,editions_error,open_library_work_id').eq('id',bookId).single();let existing=(await admin.from('editions').select('*').eq('book_id',bookId)).data||[];const fresh=sq.data?.editions_last_refreshed_at&&Date.now()-new Date(sq.data.editions_last_refreshed_at).getTime()<30*86400000;if(!force&&fresh&&existing.length>3)return json({ok:true,cached:true,status:sq.data?.editions_status,count:existing.length,editions:existing});await admin.from('books').update({editions_status:'refreshing',editions_error:null}).eq('id',bookId);
 const title=book.title,author=String(book.authors||'').split(',')[0].trim(),selectedIsbn=isbn(book.isbn13||book.isbn10),raw:any[]=[];let workId=sq.data?.open_library_work_id||existing.map((e:any)=>e.open_library_work_id).find(Boolean)||null;
 if(!workId&&selectedIsbn&&valid(selectedIsbn)){const e=await fj(`https://openlibrary.org/isbn/${encodeURIComponent(selectedIsbn)}.json`,7000);workId=String(e?.works?.[0]?.key||'').match(/\/works\/(OL\d+W)/)?.[1]||null}
 if(!workId){const u=new URL('https://openlibrary.org/search.json');u.searchParams.set('title',title);if(author)u.searchParams.set('author',author);u.searchParams.set('limit','10');u.searchParams.set('fields','key,title,author_name');const s=await fj(u.toString(),8000);let best:any=null,bs=0;for(const d of(Array.isArray(s?.docs)?s.docs:[])){const sc=sim(title,d.title)*.76+authorSim(author,d.author_name||[])*.24;if(sc>bs){best=d;bs=sc}}if(best&&bs>=.7)workId=String(best.key||'').match(/\/works\/(OL\d+W)/)?.[1]||null}
 let olCount=0;if(workId){for(const off of[0,50]){const d=await fj(`https://openlibrary.org/works/${workId}/editions.json?limit=50&offset=${off}`,11000);const rows=Array.isArray(d?.entries)?d.entries:[];olCount+=rows.length;for(const e of rows){const ids=[...(e?.isbn_13||[]),...(e?.isbn_10||[])].map(isbn).filter(valid),cover=olCover(e);raw.push({open_library_edition_id:String(e?.key||'').match(/\/books\/(OL\d+M)/)?.[1]||null,open_library_work_id:workId,isbn13:ids.find((x:string)=>x.length===13)||null,isbn10:ids.find((x:string)=>x.length===10)||null,publisher:Array.isArray(e?.publishers)?(typeof e.publishers[0]==='string'?e.publishers[0]:e.publishers[0]?.name||null):null,publication_year:year(e?.publish_date),publication_date:null,language:lang(Array.isArray(e?.languages)?String(e.languages[0]?.key||'').split('/').pop():null),format:fmt(e?.physical_format),binding:fmt(e?.physical_format),edition_statement:clean(e?.edition_name)||null,page_count:Number(e?.number_of_pages||0)||null,cover_url:cover,cover_source:cover?'Open Library':null,metadata_source:'edition_browser_v6_ol',metadata_match_confidence:'Same Open Library work',metadata_payload:{open_library:e}})}if(rows.length<50)break}}
 const gqs=[`intitle:"${title}"${author?` inauthor:"${author}"`:''}`,`"${title}"${author?` "${author}"`:''}`];let googleCount=0;for(const q of gqs){const u=new URL('https://www.googleapis.com/books/v1/volumes');u.searchParams.set('q',q);u.searchParams.set('maxResults','40');u.searchParams.set('projection','full');const g=await fj(u.toString(),9000);for(const item of(Array.isArray(g?.items)?g.items:[])){const v=item?.volumeInfo||{},authors=Array.isArray(v.authors)?v.authors:[],ts=sim(title,v.title),as=authorSim(author,authors);if(ts<.72||as<.4)continue;const i13=isbn(gid(v,'ISBN_13')),i10=isbn(gid(v,'ISBN_10'));if(!valid(i13)&&!valid(i10))continue;googleCount++;raw.push({google_books_volume_id:item.id||null,isbn13:valid(i13)?i13:null,isbn10:valid(i10)?i10:null,publisher:v.publisher||null,publication_year:year(v.publishedDate),publication_date:/^\d{4}-\d{2}-\d{2}$/.test(String(v.publishedDate||''))?v.publishedDate:null,language:lang(v.language),format:null,binding:null,edition_statement:null,page_count:Number(v.pageCount||0)||null,cover_url:gcover(v),cover_source:gcover(v)?'Google Books':null,metadata_source:'edition_browser_v6_google',metadata_match_confidence:`${Math.round((ts*.76+as*.24)*100)}% match`,metadata_payload:{google_books:item}})}}
 const merged:any[]=[];for(const c of raw){const m=merged.find(x=>same(x,c));if(!m){merged.push({...c});continue}for(const [k,v] of Object.entries(c))if((m[k]==null||m[k]==='')&&v!=null&&v!=='')m[k]=v;m.metadata_payload={...(m.metadata_payload||{}),...(c.metadata_payload||{})};if(!m.cover_url&&c.cover_url){m.cover_url=c.cover_url;m.cover_source=c.cover_source}}
 let inserted=0,updated=0;for(const c of merged){const m=existing.find((e:any)=>same(e,c));if(m){const p:any={metadata_last_fetched_at:new Date().toISOString()};for(const k of['open_library_edition_id','open_library_work_id','google_books_volume_id','isbn13','isbn10','publisher','publication_year','publication_date','language','format','binding','edition_statement','page_count'])if(!m[k]&&c[k]!=null)p[k]=c[k];if(!m.cover_locked&&!m.cover_url&&c.cover_url){p.cover_url=c.cover_url;p.cover_source=c.cover_source;p.cover_verified=true}if(Object.keys(p).length>1){const u=await admin.from('editions').update(p).eq('id',m.id);if(!u.error){Object.assign(m,p);updated++}}continue}const ins=await admin.from('editions').insert({book_id:bookId,owned:false,preferred_copy:false,is_reference:false,cover_verified:Boolean(c.cover_url),metadata_last_fetched_at:new Date().toISOString(),...c}).select('*').single();if(!ins.error&&ins.data){existing.push(ins.data);inserted++}}
 const status=existing.length>1?'ready':merged.length?'partial':existing.length?'partial':'failed';const err=status==='failed'?'No editions could be discovered from Open Library or Google Books.':status==='partial'?'Only one edition is currently known.':null;await admin.from('books').update({editions_status:status,editions_last_refreshed_at:new Date().toISOString(),editions_error:err,open_library_work_id:workId||sq.data?.open_library_work_id||null}).eq('id',bookId);const final=(await admin.from('editions').select('*').eq('book_id',bookId).order('owned',{ascending:false}).order('preferred_copy',{ascending:false}).order('publication_year',{ascending:false})).data||[];return json({ok:status!=='failed',status,count:final.length,inserted,updated,work_id:workId,source_counts:{open_library:olCount,google_books:googleCount,candidates:merged.length},editions:final,message:err});
}catch(e){console.error(e);if(admin&&bookId)try{await admin.from('books').update({editions_status:'failed',editions_error:e?.message||'Edition discovery failed'}).eq('id',bookId)}catch{}return json({error:e?.message||'Edition discovery failed'},500)}});
