import { createClient } from 'https://esm.sh/@supabase/supabase-js@2.57.4';

const CORS={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'authorization, x-client-info, apikey, content-type','Access-Control-Allow-Methods':'POST, OPTIONS'};
const json=(b:unknown,s=200)=>new Response(JSON.stringify(b),{status:s,headers:{...CORS,'Content-Type':'application/json'}});
const norm=(v:any)=>String(v??'').toLowerCase().normalize('NFKD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9 ]/g,' ').replace(/\s+/g,' ').trim().replace(/^(the|a|an)\s+/,'');
const cleanIsbn=(v:any)=>String(v??'').replace(/[^0-9Xx]/g,'').toUpperCase();
function valid(i:string){if(/^\d{13}$/.test(i)){const s=i.slice(0,12).split('').reduce((a,c,n)=>a+Number(c)*(n%2?3:1),0);return(10-s%10)%10===Number(i[12])}if(/^\d{9}[\dX]$/.test(i)){let s=0;for(let n=0;n<10;n++)s+=(i[n]==='X'?10:Number(i[n]))*(10-n);return s%11===0}return false}
function sim(a:any,b:any){const aa=norm(a),bb=norm(b);if(!aa||!bb)return 0;if(aa===bb)return 1;if(aa.includes(bb)||bb.includes(aa))return .96;const A=new Set(aa.split(' ').filter((x:string)=>x.length>1)),B=new Set(bb.split(' ').filter((x:string)=>x.length>1));if(!A.size||!B.size)return 0;return[...A].filter(x=>B.has(x)).length/Math.max(A.size,B.size)}
function authorSim(t:string,arr:string[]){if(!t)return .8;let best=0;for(const a of arr){best=Math.max(best,sim(t,a));const x=norm(t).split(' ').at(-1),y=norm(a).split(' ').at(-1);if(x&&y&&x===y)best=Math.max(best,.94)}return best}
async function fetchAny(url:string,ms=9000){const c=new AbortController(),t=setTimeout(()=>c.abort(),ms);try{const r=await fetch(url,{signal:c.signal,redirect:'follow',headers:{'User-Agent':'ReadingRoom/8.0 (personal library catalogue)','Accept':'application/json,text/html;q=0.9,*/*;q=0.8'}});if(!r.ok)return null;const ct=r.headers.get('content-type')||'';return ct.includes('json')?await r.json():await r.text()}catch{return null}finally{clearTimeout(t)}}
const text=(v:any)=>{const s=String(v??'').replace(/<[^>]+>/g,' ').replace(/\s+/g,' ').trim();return s?(s.length>3000?s.slice(0,2997)+'…':s):null};
function allMeta(html:string,name:string){const out:string[]=[];const n=name.replace(/[.*+?^${}()|[\]\\]/g,'\\$&');const rx=new RegExp(`<meta[^>]+(?:name|property)=["']${n}["'][^>]+content=["']([^"']+)["'][^>]*>|<meta[^>]+content=["']([^"']+)["'][^>]+(?:name|property)=["']${n}["'][^>]*>`,'gi');let m;while((m=rx.exec(html)))out.push((m[1]||m[2]||'').replace(/&amp;/g,'&').replace(/&quot;/g,'"').replace(/&#39;/g,"'"));return out}
const meta=(h:string,n:string)=>allMeta(h,n)[0]||null;
function year(item:any){const d=item?.published?.['date-parts']?.[0]||item?.['published-print']?.['date-parts']?.[0]||item?.['published-online']?.['date-parts']?.[0]||[];return Number(d[0])||null}

Deno.serve(async(req:Request)=>{if(req.method==='OPTIONS')return new Response('ok',{headers:CORS});if(req.method!=='POST')return json({error:'POST required'},405);try{
 const url=Deno.env.get('SUPABASE_URL')!,anon=Deno.env.get('SUPABASE_ANON_KEY')!,auth=req.headers.get('Authorization');if(!auth)return json({error:'Authentication required'},401);const user=createClient(url,anon,{global:{headers:{Authorization:auth}}});const ud=await user.auth.getUser();if(ud.error||!ud.data.user)return json({error:'Invalid session'},401);const own=await user.rpc('is_library_owner');if(own.error||own.data!==true)return json({error:'Not authorized'},403);
 const body=await req.json(),q=String(body?.query||'').trim(),author=String(body?.author||'').trim();if(!q)return json({error:'Enter a title.'},400);
 const u=new URL('https://api.crossref.org/works');u.searchParams.set('query.bibliographic',q);if(author)u.searchParams.set('query.author',author);u.searchParams.set('rows','25');u.searchParams.set('sort','relevance');u.searchParams.set('order','desc');
 const raw=await fetchAny(u.toString(),10000);const items=Array.isArray((raw as any)?.message?.items)?(raw as any).message.items:[];
 let rows:any[]=[];
 for(const item of items){const title=String(Array.isArray(item?.title)?item.title[0]||'':'').trim();if(!title)continue;const authors=(Array.isArray(item?.author)?item.author:[]).map((a:any)=>[a.given,a.family].filter(Boolean).join(' ').trim()).filter(Boolean);const ts=sim(q,title),as=author?authorSim(author,authors):.8;if(ts<.48||(author&&as<.45))continue;const ids=(Array.isArray(item?.ISBN)?item.ISBN:[]).map(cleanIsbn).filter(valid);if(!ids.length)continue;rows.push({item,title,authors,ts,as,score:ts*.78+as*.22,isbn13:ids.find((x:string)=>x.length===13)||null,isbn10:ids.find((x:string)=>x.length===10)||null})}
 rows=rows.sort((a,b)=>b.score-a.score).slice(0,8);
 const results=await Promise.all(rows.map(async(r:any)=>{const item=r.item,doi=item?.DOI||null;let html:any=null;if(doi)html=await fetchAny(`https://doi.org/${encodeURIComponent(doi)}`,6500);const h=typeof html==='string'?html:'';const pageIsbns=allMeta(h,'citation_isbn').map(cleanIsbn).filter(valid);const page13=pageIsbns.find(x=>x.length===13)||null,page10=pageIsbns.find(x=>x.length===10)||null;const cover=meta(h,'og:image')||meta(h,'twitter:image');const synopsis=text(meta(h,'description')||meta(h,'og:description')||item?.abstract);const pub=meta(h,'citation_publisher')||item?.publisher||null;const date=meta(h,'citation_publication_date')||meta(h,'citation_date');const pageText=meta(h,'citation_pages')||String(item?.page||'');const pageMatch=pageText.match(/^(\d+)(?:\D|$)/);return{title:r.title,subtitle:Array.isArray(item?.subtitle)?item.subtitle[0]||null:null,authors:r.authors,isbn13:page13||r.isbn13,isbn10:page10||r.isbn10,publisher:pub,publication_year:(date?.match(/(1[0-9]{3}|20[0-9]{2}|2100)/)?.[1]?Number(date.match(/(1[0-9]{3}|20[0-9]{2}|2100)/)![1]):year(item)),page_count:pageMatch?Number(pageMatch[1]):null,format:'Book',cover_url:cover||null,synopsis,primary_genre:'Book',language:item?.language||null,provider:'Crossref / Publisher',provider_id:doi,score:r.score+.03,already_in_library:false}}));
 return json({ok:true,query:q,results:results.slice(0,10),provider:'crossref'});
 }catch(e){console.error(e);return json({error:(e as any)?.message||'Fallback book search failed.'},500)}});
