create table public.reading_system_events (
  id bigint generated by default as identity primary key,
  occurred_at timestamptz not null default now(),
  component text not null check (btrim(component) <> ''),
  action text not null check (btrim(action) <> ''),
  outcome text not null check (btrim(outcome) <> ''),
  error_code text,
  http_status integer check (http_status is null or http_status between 100 and 599),
  duration_ms integer check (duration_ms is null or duration_ms >= 0),
  book_id uuid,
  edition_id uuid,
  metadata jsonb not null default '{}'::jsonb check (jsonb_typeof(metadata) = 'object')
);

comment on table public.reading_system_events is
  'Small, secret-free operational event stream for Reading Check-in and chapter-map diagnostics.';
comment on column public.reading_system_events.metadata is
  'Operational facts only. Never store credentials, URLs, request bodies, note text, snapshots, client identifiers, or chapter content.';

create index reading_system_events_occurred_at_idx
  on public.reading_system_events (occurred_at desc);
create index reading_system_events_component_occurred_at_idx
  on public.reading_system_events (component, occurred_at desc);
create index reading_system_events_action_occurred_at_idx
  on public.reading_system_events (action, occurred_at desc);

alter table public.reading_system_events enable row level security;

revoke all on table public.reading_system_events from public, anon, authenticated;
revoke all on sequence public.reading_system_events_id_seq from public, anon, authenticated;
grant select on table public.reading_system_events to authenticated;
grant select, insert on table public.reading_system_events to service_role;
grant usage, select on sequence public.reading_system_events_id_seq to service_role;

create policy reading_system_events_owner_select
on public.reading_system_events
for select
to authenticated
using (public.is_library_owner());

-- Let only current-reading editions with a prior unsuccessful, empty map make one
-- fresh attempt under the new conservative same-work fallback. The attempt writes
-- a new timestamp and normal cooldown behaviour resumes immediately afterward.
update public.editions e
set chapter_map_last_checked_at = null
where e.chapter_map_status = 'not_found'
  and e.chapter_map_last_checked_at < statement_timestamp()
  and not exists (
    select 1 from public.edition_chapters ec where ec.edition_id = e.id
  )
  and exists (
    select 1
    from public.library_entries le
    where le.current_edition_id = e.id
      and le.overall_status = 'Currently Reading'
  );
