import test from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { enrichmentDb } from '../helpers/enrichment-db.js';

test('stability migration executes cover transactions, lock protection and manual-edition validation in PostgreSQL',async t=>{
 const db=await enrichmentDb();t.after(()=>db.close());
 await db.exec(`create function public.record_reading_checkin_bridge(uuid,uuid,text,integer,integer,text) returns jsonb language sql security definer as $$ select '{}'::jsonb $$;grant execute on function public.record_reading_checkin_bridge(uuid,uuid,text,integer,integer,text) to authenticated;`);
 for(const file of ['20260908061803_add_browse_and_switch_editions.sql','20260909181552_book_quotes_and_passages.sql','20260908071456_verified_copy_page_count_and_cover_lock.sql','20261009202447_secure_reading_checkin_bridge.sql'])await db.exec(await readFile(`supabase/migrations/${file}`,'utf8'));
 await db.exec(await readFile('tests/fixtures/v-library-production.sql','utf8'));
 await db.exec(await readFile('supabase/migrations/20261009184736_reading_room_stability.sql','utf8'));
 assert.match((await db.query("select pg_get_viewdef('public.v_library'::regclass,true) definition")).rows[0].definition,/lower\(x.provider\).*goodreads/);
 const uid='10000000-0000-0000-0000-000000000001';
 await db.exec(`create or replace function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;insert into auth.users values('${uid}');update private.app_state set owner_user_id='${uid}';select set_config('request.jwt.claim.sub','${uid}',false);grant usage on schema auth,private to authenticated;grant execute on function private.is_owner() to authenticated;`);
 const book=(await db.query("insert into books(title) values('Yeti: An Abominable History') returning id")).rows[0].id;
 await db.query('insert into library_entries(user_id,book_id) values($1,$2)',[uid,book]);
 assert.equal((await db.query('select claim_edition_discovery($1) claimed',[book])).rows[0].claimed,true);
 assert.equal((await db.query('select claim_edition_discovery($1) claimed',[book])).rows[0].claimed,false);
 const args=[book,'9780008279493','William Collins',2018,null,320,null,null,'https://www.psbooks.co.uk/yeti'];
 const manual=async values=>(await db.query('select add_manual_edition($1,$2,$3,$4,$5,$6,$7,$8,$9) id',values)).rows[0].id;
 const id=await manual(args);assert.equal(await manual([book,'0008279497',...args.slice(2)]),id);
 assert.equal((await db.query('select count(*) n from editions where book_id=$1',[book])).rows[0].n,1);
 assert.equal((await db.query('select format from editions where id=$1',[id])).rows[0].format,null);
 await assert.rejects(manual([book,'9780008279494',...args.slice(2)]),/checksum/);
 await assert.rejects(manual([book,'1234567890128',...args.slice(2)]),/Invalid ISBN/);
 const otherBook=(await db.query("insert into books(title) values('Different book') returning id")).rows[0].id;
 await db.query('insert into library_entries(user_id,book_id) values($1,$2)',[uid,otherBook]);
 await assert.rejects(manual([otherBook,...args.slice(1)]),/another book/);
 await db.query('select save_cover_selection($1,$2,null,$3,$4,$5,true,true)',[uid,book,'https://covers.example/one.jpg','Uploaded image','Test']);
 await db.query("update books set cover_url_preferred='https://automatic.example/cover.jpg',cover_locked=false where id=$1",[book]);
 assert.equal((await db.query('select cover_url_preferred from books where id=$1',[book])).rows[0].cover_url_preferred,'https://covers.example/one.jpg');
 await db.query("update editions set cover_url='https://edition.example/auto.jpg' where id=$1",[id]);
 await db.query('update books set reference_edition_id=$2 where id=$1',[book,id]);
 assert.equal((await db.query('select cover_url,cover_locked from v_library where id=$1',[book])).rows[0].cover_url,'https://covers.example/one.jpg');
 await db.query('select save_cover_selection($1,$2,$3,$4,$5,$6,true,true)',[uid,book,id,'https://covers.example/two.jpg','Uploaded image','Replacement']);
 assert.equal((await db.query('select count(*) n from book_cover_candidates where book_id=$1 and selected',[book])).rows[0].n,1);
 assert.equal((await db.query('select cover_url from v_library where id=$1',[book])).rows[0].cover_url,'https://covers.example/two.jpg');
 await assert.rejects(db.query('select save_cover_selection($1,$2,$3,$4,$5,$6,true,true)',[uid,book,uid,'https://covers.example/bad.jpg','Uploaded image','Bad']),/Edition does not belong/);
 assert.equal((await db.query('select cover_url from v_library where id=$1',[book])).rows[0].cover_url,'https://covers.example/two.jpg');
 assert.equal((await db.query("select has_function_privilege('anon','public.record_reading_checkin_bridge(uuid,uuid,text,integer,integer,text)','execute') allowed")).rows[0].allowed,false);
 const switched=(await db.query("insert into editions(book_id,isbn13,cover_url,cover_source,cover_verified,page_count) values($1,'9780008279516','https://edition.example/verified.jpg','Open Library',true,320) returning id",[book])).rows[0].id;
 await db.query('select verify_owned_edition($1,$2)',[book,switched]);
 const selected=(await db.query('select cover_url,cover_source,cover_verified,current_edition_id from v_library where id=$1',[book])).rows[0];
 assert.equal(selected.cover_url,'https://edition.example/verified.jpg');assert.equal(selected.cover_source,'Open Library');assert.equal(selected.cover_verified,true);assert.equal(selected.current_edition_id,switched);
 await db.query("update books set cover_url_preferred='https://automatic.example/other.jpg',cover_locked=false where id=$1",[book]);
 assert.equal((await db.query('select cover_url from v_library where id=$1',[book])).rows[0].cover_url,'https://edition.example/verified.jpg');
 await db.exec("set role authenticated;select set_config('request.jwt.claim.sub','10000000-0000-0000-0000-000000000002',false)");await assert.rejects(manual(args),/Not authorized/);await db.exec('reset role');
 await db.exec("set role anon");await assert.rejects(manual(args),/permission denied/);await db.exec('reset role');
});
