import { createClient } from 'https://esm.sh/@supabase/supabase-js@2.57.4';
const CORS={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'authorization, x-client-info, apikey, content-type','Access-Control-Allow-Methods':'POST, OPTIONS'};
const json=(b:unknown,s=200)=>new Response(JSON.stringify(b),{status:s,headers:{...CORS,'Content-Type':'application/json'}});
const clean=(v:any)=>String(v??'').replace(/<[^>]+>/g,' ').replace(/\s+/g,' ').trim();
const norm=(v:any)=>clean(v).toLowerCase().normalize('NFKD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9 ]/g,' ').replace(/\s+/g,' ').trim().replace(/^(the|a|an)\s+/,'');
const isbn=(v:any)=>String(v??'').replace(/[^0-9Xx]/g,'').toUpperCase();
const year=(v:any)=>{const m=String(v??'').match(/(?:^|\D)(1[0-9]{3}|20[0-9]{2}|2100)(?:\D|$)/);return m?Number(m[1]):null};
const desc=(v:any)=>{const t=clean(typeof v==='string'?v:v?.value);return t?(t.length<=3000?t:t.slice(0,2997)+'…'):null};
function valid(i:string){if(/^\d{13}$/.test(i)){const s=i.slice(0,12).split('').reduce((a,c,n)=>a+Number(c)*(n%2?3:1),0);return(10-s%10)%10===Number(i[12])}if(/^\d{9}[\dX]$/.test(i)){let s=0;for(let n=0;n<10;n++)s+=(i[n]==='X'?10:Number(i[n]))*(10-n);return s%11===0}return false}
function sim(a:any,b:any){const A=norm(a),B=norm(b);if(!A||!B)return 0;if(A===B)return 1;if(A.includes(B)||B.includes(A))return .96;const as=new Set(A.split(' ').filter((x:string)=>x.length>1)),bs=new Set(B.split(' ').filter((x:string)=>x.length>1));return[...as].filter(x=>bs.has(x)).length/Math.max(as.size,bs.size)}
function authorSim(target:any,cands:any[]=[]){if(!target)return .75;let best=0;for(const c of cands){best=Math.max(best,sim(target,c));const a=norm(target).split(' ').at(-1),b=norm(c).split(' ').at(-1);if(a&&b&&a===b)best=Math.max(best,.92)}return best}
async function fj(url:string,ms=8500,asText=false){const c=new AbortController(),t=setTimeout(()=>c.abort(),ms);try{const r=await fetch(url,{signal:c.signal,redirect:'follow',headers:{'User-Agent':'Mozilla/5.0 (compatible; ReadingRoom/7.0; +personal-library)','Accept':asText?'text/html,application/xhtml+xml;q=0.9,*/*;q=0.8':'application/json,*/*;q=0.8'}});if(!r.ok)return null;return asText?await r.text():await r.json()}catch{return null}finally{clearTimeout(t)}}
const gid=(v:any,t:string)=>v?.industryIdentifiers?.find((x:any)=>x?.type===t)?.identifier??null;
const gcover=(v:any)=>{const l=v?.imageLinks||{};return[l.extraLarge,l.large,l.medium,l.small,l.thumbnail,l.smallThumbnail].find(Boolean)?.replace(/^http:/,'https:')||null};
async function google(q:string){const u=new URL('https://www.googleapis.com/books/v1/volumes');u.searchParams.set('q',q);u.searchParams.set('maxResults','40');u.searchParams.set('projection','full');return fj(u.toString(),9000)}
async function googleVolume(id:string){return id?fj(`https://www.googleapis.com/books/v1/volumes/${encodeURIComponent(id)}`,7500):null}
function candidate(item:any,title:string,author:string,requestedIsbn=''){const v=item?.volumeInfo||{},authors=Array.isArray(v.authors)?v.authors:[],i13=isbn(gid(v,'ISBN_13')),i10=isbn(gid(v,'ISBN_10')),ids=[i13,i10].filter(valid),exact=Boolean(requestedIsbn&&ids.includes(requestedIsbn)),ts=sim(title,v.title),as=authorSim(author,authors);return{item,v,title:v.title||'',authors,isbn13:valid(i13)?i13:null,isbn10:valid(i10)?i10:null,exact,score:exact?1:ts*.76+as*.24};}
async function upsertRating(admin:any,bookId:string,row:any){if(row?.rating_5==null||!Number.isFinite(Number(row.rating_5)))return false;const payload={book_id:bookId,provider:row.provider,rating_5:Number(row.rating_5),rating_count:row.rating_count==null?null:Number(row.rating_count),review_count:row.review_count==null?null:Number(row.review_count),source_url:row.source_url||null,provider_book_id:row.provider_book_id||null,is_primary:Boolean(row.is_primary),fetched_at:new Date().toISOString(),notes:row.notes||null};const {error}=await admin.from('public_ratings').upsert(payload,{onConflict:'book_id,provider'});return !error;}
async function openLibraryRating(admin:any,bookId:string,workId:string|null){if(!workId)return null;const r=await fj(`https://openlibrary.org/works/${encodeURIComponent(workId)}/ratings.json`,6500);const avg=Number(r?.summary?.average),count=Number(r?.summary?.count);if(!Number.isFinite(avg)||!count)return null;const row={provider:'Open Library',rating_5:avg,rating_count:count,review_count:null,source_url:`https://openlibrary.org/works/${workId}`,provider_book_id:workId,is_primary:false,notes:'Automatically refreshed from Open Library work ratings.'};await upsertRating(admin,bookId,row);return row;}
function ldJson(html:string){const blocks=[...html.matchAll(/<script[^>]+type=["']application\/ld\+json["'][^>]*>([\s\S]*?)<\/script>/gi)].map(m=>m[1]);for(const raw of blocks){try{const x=JSON.parse(raw.trim());const items=Array.isArray(x)?x:[x];for(const obj of items){if(obj?.aggregateRating)return obj;if(Array.isArray(obj?.['@graph'])){const h=obj['@graph'].find((z:any)=>z?.aggregateRating);if(h)return h}}}catch{}}return null}
async function goodreadsRating(admin:any,bookId:string,title:string,author:string,bookIsbn:string){const query=bookIsbn||`${title} ${author}`;const search=await fj(`https://www.goodreads.com/search?q=${encodeURIComponent(query)}`,6500,true);if(typeof search!=='string')return null;const matches=[...search.matchAll(/href=["'](\/book\/show\/[^"'#?]+)["']/gi)].map(m=>m[1]);if(!matches.length)return null;for(const path of matches.slice(0,3)){const page=await fj(`https://www.goodreads.com${path}`,6500,true);if(typeof page!=='string')continue;const data=ldJson(page);if(!data)continue;const pageTitle=String(data.name||data.headline||'');const pageAuthors=Array.isArray(data.author)?data.author.map((a:any)=>a?.name||''):[data.author?.name||''];if(sim(title,pageTitle)<.68||authorSim(author,pageAuthors)<.55)continue;const a=data.aggregateRating||{},rating=Number(a.ratingValue),count=Number(a.ratingCount),reviews=Number(a.reviewCount);if(!Number.isFinite(rating)||!count)continue;const id=String(path).match(/\/book\/show\/(\d+)/)?.[1]||null;const row={provider:'Goodreads',rating_5:rating,rating_count:count,review_count:Number.isFinite(reviews)?reviews:null,source_url:`https://www.goodreads.com${path}`,provider_book_id:id,is_primary:true,notes:'Automatically refreshed from public Goodreads book metadata.'};await admin.from('public_ratings').update({is_primary:false}).eq('book_id',bookId).neq('provider','Goodreads');await upsertRating(admin,bookId,row);return row;}return null}

Deno.serve(async(req:Request)=>{if(req.method==='OPTIONS')return new Response('ok',{headers:CORS});if(req.method!=='POST')return json({error:'POST required'},405);let admin:any,bookId='';try{
 const auth=req.headers.get('Authorization');if(!auth)return json({error:'Authentication required'},401);const url=Deno.env.get('SUPABASE_URL')!,anon=Deno.env.get('SUPABASE_ANON_KEY')!,service=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;const user=createClient(url,anon,{global:{headers:{Authorization:auth}}});const ud=await user.auth.getUser();if(ud.error||!ud.data.user)return json({error:'Invalid session'},401);const own=await user.rpc('is_library_owner');if(own.error||own.data!==true)return json({error:'Not authorized'},403);admin=createClient(url,service);
 const body=await req.json();bookId=String(body?.book_id||'');if(!bookId)return json({error:'book_id required'},400);const q=await admin.from('v_library').select('*').eq('id',bookId).single();if(q.error||!q.data)return json({error:'Book not found'},404);const b=q.data;const core=await admin.from('books').select('cover_locked,synopsis,metadata_status,reference_edition_id').eq('id',bookId).single();
 await admin.from('books').update({metadata_status:'resolving',metadata_last_attempted_at:new Date().toISOString(),metadata_error:null}).eq('id',bookId);
 const title=b.title,author=String(b.authors||'').split(',')[0].trim(),existing=isbn(b.isbn13||b.isbn10),queries:string[]=[];if(existing&&valid(existing))queries.push(`isbn:${existing}`);queries.push(`intitle:"${title}"${author?` inauthor:"${author}"`:''}`,`"${title}"${author?` "${author}"`:''}`);
 const [storedVolume,...gs]=await Promise.all([googleVolume(String(b.google_books_volume_id||'')),...queries.map(google)]);let cs:any[]=[];if(storedVolume?.volumeInfo){const c=candidate(storedVolume,title,author,existing);if(c.score>=.58)cs.push({...c,score:Math.max(c.score,.92)})}for(const g of gs)for(const it of(Array.isArray(g?.items)?g.items:[])){const c=candidate(it,title,author,existing);if(c.title&&c.score>=.45&&(c.isbn13||c.isbn10))cs.push(c)}cs.sort((a,b)=>b.score-a.score);
 const dedup=new Map<string,any>();for(const c of cs){const k=c.isbn13||c.isbn10||c.item?.id;if(!dedup.has(k)||c.score>dedup.get(k).score)dedup.set(k,c)}cs=[...dedup.values()].sort((a,b)=>b.score-a.score);let top=cs[0]||null;
 let ol:any=null,work:any=null,workKey:string|null=b.open_library_work_id||null;if(existing&&valid(existing)){ol=await fj(`https://openlibrary.org/isbn/${encodeURIComponent(existing)}.json`,7000);workKey=workKey||ol?.works?.[0]?.key?.split('/').pop()||null;}if(workKey)work=await fj(`https://openlibrary.org/works/${encodeURIComponent(workKey)}.json`,5500);
 const ratingJobs=[openLibraryRating(admin,bookId,workKey),goodreadsRating(admin,bookId,title,author,existing)].map(p=>p.catch(()=>null));
 if(!top||top.score<.64){await Promise.allSettled(ratingJobs);const hasUsable=Boolean(b.synopsis||b.cover_url||b.display_edition_id||existing);await admin.from('books').update({metadata_status:hasUsable?'partial':'failed',metadata_retry_after:new Date(Date.now()+6*60*60*1000).toISOString(),metadata_error:hasUsable?'Provider refresh could not improve the existing verified record.':'No reliable Google Books/Open Library match'}).eq('id',bookId);return json({ok:hasUsable,status:hasUsable?'partial':'failed',message:hasUsable?'Existing metadata preserved; providers returned no better match.':'No reliable metadata match found.'});}
 const v=top.v||{},synopsis=b.synopsis||desc(v.description)||desc(work?.description)||null,olCover=Array.isArray(ol?.covers)&&ol.covers[0]?`https://covers.openlibrary.org/b/id/${ol.covers[0]}-L.jpg?default=false`:Array.isArray(work?.covers)&&work.covers[0]>0?`https://covers.openlibrary.org/b/id/${work.covers[0]}-L.jpg?default=false`:null,cover=b.cover_url||gcover(v)||olCover||null,pageCount=Number(v.pageCount||ol?.number_of_pages||b.total_pages||0)||null,i13=top.isbn13||null,i10=top.isbn10||null,olEditionId=String(ol?.key||'').match(/\/books\/(OL\d+M)/)?.[1]||null,olWorkId=workKey||null;
 let editionId=b.display_edition_id||null;if(!editionId&&(i13||i10)){const filt=[i13?`isbn13.eq.${i13}`:null,i10?`isbn10.eq.${i10}`:null].filter(Boolean).join(',');const ex=await admin.from('editions').select('id,book_id').or(filt).maybeSingle();if(ex.data?.book_id===bookId)editionId=ex.data.id;else if(!ex.data){const ins=await admin.from('editions').insert({book_id:bookId,owned:false,preferred_copy:false,is_reference:true,isbn13:i13,isbn10:i10,publisher:v.publisher||null,publication_year:year(v.publishedDate),language:v.language||null,format:v.printType||null,page_count:pageCount,cover_url:cover,cover_source:cover?'Google Books/Open Library':null,cover_verified:Boolean(cover),google_books_volume_id:top.item?.id||null,open_library_edition_id:olEditionId,open_library_work_id:olWorkId,metadata_source:'resolver_v7',metadata_last_fetched_at:new Date().toISOString(),metadata_match_confidence:`${Math.round(top.score*100)}% match`,metadata_payload:{google_books:top.item,open_library:ol,open_library_work:work}}).select('id').single();if(!ins.error)editionId=ins.data.id}}
 if(editionId){const eq=await admin.from('editions').select('cover_locked').eq('id',editionId).single();const p:any={metadata_last_fetched_at:new Date().toISOString(),metadata_source:'resolver_v7'};if(!b.isbn13&&i13)p.isbn13=i13;if(!b.isbn10&&i10)p.isbn10=i10;if(!b.publisher&&v.publisher)p.publisher=v.publisher;if(!b.edition_year&&year(v.publishedDate))p.publication_year=year(v.publishedDate);if(!b.edition_page_count&&pageCount)p.page_count=pageCount;if(!b.google_books_volume_id&&top.item?.id)p.google_books_volume_id=top.item.id;if(!b.open_library_edition_id&&olEditionId)p.open_library_edition_id=olEditionId;if(!b.open_library_work_id&&olWorkId)p.open_library_work_id=olWorkId;if(!eq.data?.cover_locked&&!b.cover_url&&cover){p.cover_url=cover;p.cover_source='Google Books/Open Library';p.cover_verified=true}await admin.from('editions').update(p).eq('id',editionId)}
 const bp:any={metadata_status:'resolved',metadata_confidence:top.score,metadata_resolved_at:new Date().toISOString(),metadata_retry_after:null,metadata_error:null,metadata_source:'resolver_v7',metadata_last_updated:new Date().toISOString().slice(0,10)};if(!b.synopsis&&synopsis)bp.synopsis=synopsis;if(!core.data?.reference_edition_id&&b.ownership_status!=='Owned'&&editionId)bp.reference_edition_id=editionId;if(!core.data?.cover_locked&&!b.cover_url&&cover){bp.cover_url_preferred=cover;bp.cover_source='Google Books/Open Library';bp.cover_verified=true}if(!b.primary_genre&&Array.isArray(v.categories)&&v.categories[0])bp.primary_genre=v.categories[0];if(!b.language&&v.language)bp.language=v.language;await admin.from('books').update(bp).eq('id',bookId);if(pageCount&&!b.total_pages)await admin.from('library_entries').update({total_pages:pageCount}).eq('book_id',bookId);
 if(v.averageRating!=null)await upsertRating(admin,bookId,{provider:'Google Books',rating_5:Number(v.averageRating),rating_count:v.ratingsCount??null,review_count:null,source_url:v.infoLink||`https://books.google.com/books?id=${top.item?.id||''}`,provider_book_id:top.item?.id||null,is_primary:false,notes:'Automatically refreshed from Google Books.'});
 const ratingResults=await Promise.allSettled(ratingJobs);return json({ok:true,status:'resolved',book_id:bookId,edition_id:editionId,confidence:top.score,isbn13:i13,isbn10:i10,page_count:pageCount,cover_url:cover,synopsis:Boolean(synopsis),google_books_volume_id:top.item?.id||null,ratings_refreshed:ratingResults.map(x=>x.status)});
}catch(e){console.error(e);if(admin&&bookId)try{await admin.from('books').update({metadata_status:'partial',metadata_error:(e as any)?.message||'Resolver error',metadata_retry_after:new Date(Date.now()+6*60*60*1000).toISOString()}).eq('id',bookId)}catch{}return json({error:(e as any)?.message||'Content enrichment failed'},500)}});
